### PR TITLE
OboeTester: fix phase error calculation

### LINKED ISSUE #1672: OboeTester: phase difference not accounting for wrap.
I am not accounting for the circular wraparound of the phase!

Phase is in radians from -PI to +PI.
Imagine two angles, -3.14 and +3.13.
Those are actually very close. But: diff = 6.27
The actual phaseError should be only 2PI - 6.27 = 0.0131

We need a new method:

    double calculatePhaseError(double p1, double p2) {
        double diff = Math.abs(p1 - p2);
        if (diff > Math.PI) {
           diff = (Math.PI * 2) - diff;
        }
        return diff;
    }

### PR DESCRIPTION
**Pull request by philburk**
Tune the Data Paths test.

Fixes #1672

### CODE REVIEW

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java [hunk 1]
```diff
@@ -112,6 +110,14 @@ public static String comparePassedField(String prefix, Object failed, Object pas
         }
     }
 
+    public static double calculatePhaseError(double p1, double p2) {
```
Comment (robertwu1) [inline apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:113]: The diff would be negative if the diff is over 2PI. Should we do some math wrapping around if it exceeds 2PI?

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java [hunk 2]
```diff
@@ -267,16 +280,25 @@ public String didTestFail() {
...
         }
         return why;
     }
 
+    private double getAveragePhaseError() {
+        return (mPhaseErrorCount > 0) ? (mPhaseErrorSum / mPhaseErrorCount) : MAX_ALLOWED_JITTER;
+    }
+
+    private boolean isPhaseJitterValid() {
+        return mPhaseErrorCount > 4;
```
Comment (robertwu1) [inline apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:299]: Where does this 4 come from? Can we define this as a constant?

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java [hunk 3]
```diff
@@ -267,16 +280,25 @@ public String didTestFail() {
...
+        if (!isPhaseJitterValid()) {
+            why += ", jitterUnknown";
+        } else if (getAveragePhaseError() > MAX_ALLOWED_JITTER) {
+            why += ", jitterHigh";
         }
         return why;
     }
 
+    private double getAveragePhaseError() {
+        return (mPhaseErrorCount > 0) ? (mPhaseErrorSum / mPhaseErrorCount) : MAX_ALLOWED_JITTER;
```
Comment (robertwu1) [inline apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:295]: Returning MAX_ALLOWED_JITTER if there is no error feels strange

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java [hunk 4]
```diff
@@ -125,22 +131,27 @@ public void startSniffer() {
...
         @Override
         public void run() {
             mMagnitude = getMagnitude();
             mMaxMagnitude = getMaxMagnitude();
+            Log.d(TAG, String.format("magnitude = %7.4f, maxMagnitude = %7.4f",
+                    mMagnitude, mMaxMagnitude));
             // Only look at the phase if we have a signal.
             if (mMagnitude >= MIN_REQUIRED_MAGNITUDE) {
                 double phase = getPhase();
                 if (mPhaseCount > 3) {
```
Comment (robertwu1) [inline apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:148]: Where does this 3 come from?

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java [hunk 5]
```diff
@@ -267,16 +280,25 @@ public String didTestFail() {
...
-        boolean passed = true;
         if (mMaxMagnitude <= MIN_REQUIRED_MAGNITUDE) {
             why += ", mag";
         }
-        if (mPhaseJitter > MAX_ALLOWED_JITTER) {
-            why += ", jitter";
+        if (!isPhaseJitterValid()) {
+            why += ", jitterUnknown";
+        } else if (getAveragePhaseError() > MAX_ALLOWED_JITTER) {
+            why += ", jitterHigh";
```
Comment (robertwu1) [inline apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:289]: Do we want to print the average phase error here?

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java [hunk 6]
```diff
@@ -267,16 +280,25 @@ public String didTestFail() {
...
         StreamConfiguration actualOutConfig = mAudioOutTester.actualConfiguration;
-        boolean passed = true;
         if (mMaxMagnitude <= MIN_REQUIRED_MAGNITUDE) {
             why += ", mag";
         }
-        if (mPhaseJitter > MAX_ALLOWED_JITTER) {
-            why += ", jitter";
+        if (!isPhaseJitterValid()) {
+            why += ", jitterUnknown";
+        } else if (getAveragePhaseError() > MAX_ALLOWED_JITTER) {
```
Comment (robertwu1) [inline apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:288]: This statement is using getAveragePhaseError() > MAX_ALLOWED_JITTER while is finished early is using (getAveragePhaseError() < MAX_ALLOWED_JITTER). One of these be should <= or >= so the statements are opposite of one another.

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java (hunk 1 above)
Comment (philburk) [reply apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:113]: Thanks. The atan2() function will return angles in a reasonable range. But this function does not know where the angles came from and should be more robust.

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java (hunk 2 above)
Comment (philburk) [reply apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:299]: Done

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java (hunk 3 above)
Comment (philburk) [reply apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:295]: It is not that there is "no error". We just have no error measurements. I will bump up the value and comment it better.

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java (hunk 4 above)
Comment (philburk) [reply apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:148]: I added an explanation.

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java (hunk 5 above)
Comment (philburk) [reply apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:301]: I already print that on the same line. This code is just to print the reason the test failed.

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java (hunk 6 above)
Comment (philburk) [reply apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:300]: The statements are not opposite of each other. One asks whether we fail. The other code asks whether we can finish early because the results look so good.

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java [hunk 7]
```diff
@@ -79,7 +76,8 @@ public class TestDataPathsActivity  extends BaseAutoGlitchActivity {
     private double mMaxMagnitude;
     private int    mPhaseCount;
     private double mPhase;
-    private double mPhaseJitter;
+    private double mPhaseErrorSum;
+    private double mPhaseErrorCount;
```
Comment (robertwu1) [inline apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:80]: nit: mPhaseErrorCount is a confusing variable name as it makes you think this is the count of the number of phase errors. I can't think of a much better name though

**Review by robertwu1 — APPROVED** [review]

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java (hunk 7 above)
Comment (philburk) [reply apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:80]: I agree that Error has bad connotations.
And I also cannot think of a better name.
