### PR TITLE
Reinit. Audio Engine for MegaDrone on restart.

### LINKED ISSUE #521: [samples/MegaDrone] Crashes when onResume is called
MegaDrone sample crashes with the following error when onResume is called.
Test device: Samsung Galaxy S5 API 23 (MMB29M)

Steps to repro

- Run MegaDrone app
- Press power button (causing `onPause`) to be called (screen goes off)
- Press power button again (screen back on) and unlock

Expected result

- App is running as normal and can produce sound

Actual result

- App crashes with the following logcat output:

    05-22 18:46:55.797 19943-19943/com.example.oboe.megadrone A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xcc6d8510 in tid 19943 (.oboe.megadrone)

Probably related to #511

### PR DESCRIPTION
**Pull request by atneya**
Fixes #521

### CODE REVIEW

File: samples/MegaDrone/src/main/cpp/native-lib.cpp [hunk 1]
```diff
@@ -41,23 +41,23 @@ extern "C"
...
 }
 
 extern "C"
 JNIEXPORT void JNICALL
 Java_com_example_oboe_megadrone_MainActivity_stopEngine(JNIEnv *env, jobject instance) {
 
-    engine.stop();
-
+    engine->stop();
+    //delete engine;
```
Comment (philburk) [inline samples/MegaDrone/src/main/cpp/native-lib.cpp]: Where does this get deleted? Could we use a unique_ptr<>?

Comment (atneya-nair) [reply samples/MegaDrone/src/main/cpp/native-lib.cpp]: This is what I noted in the issue, I was unsure where the engine was being deleted, but when I attempted to delete again, I hit mem access errors.

**Comment by atneya** [comment]
Changed username, replying to recheck CLA

File: samples/MegaDrone/src/main/cpp/Synth.h [hunk 2]
```diff
@@ -60,13 +59,14 @@ class Synth : public IRenderableAudio {
...
+    virtual ~Synth() {
+    }
 private:
-
     // Rendering objects
     std::array<Oscillator, kNumOscillators> mOscs;
     Mixer mMixer;
-    std::shared_ptr<IRenderableAudio> mOutputStage;
+    MonoToStereo mConverter = MonoToStereo(&mMixer);
+    IRenderableAudio *mOutputStage; // This will point to either the mixer or converter
```
Comment (philburk) [inline samples/MegaDrone/src/main/cpp/Synth.h]: Can this be declared const? The pointer will not change after the constructor.

IRenderableAudio * const mOutputStage; // const pointer to mutable object

File: samples/RhythmGame/src/main/cpp/Game.h [hunk 3]
```diff
@@ -59,8 +59,8 @@ class Game : public AudioStreamCallback {
 private:
     AAssetManager& mAssetManager;
     AudioStream *mAudioStream { nullptr };
-    std::shared_ptr<Player> mClap;
-    std::shared_ptr<Player> mBackingTrack;
+    Player *mClap;
```
Comment (philburk) [inline samples/RhythmGame/src/main/cpp/Game.h]: unique_ptr<> is another option

File: samples/shared/Mixer.h [hunk 4]
```diff
@@ -45,15 +45,15 @@ class Mixer : public IRenderableAudio {
         }
     }
```
Comment (philburk) [inline samples/shared/Mixer.h]: Add comment that ownership must be managed by the caller. Do not delete the render while in use.

File: samples/MegaDrone/src/main/cpp/Synth.h [hunk 5]
```diff
@@ -22,6 +22,7 @@
 #include "shared/Oscillator.h"
 #include "shared/Mixer.h"
 #include "shared/MonoToStereo.h"
+#include "../../../../../src/common/OboeDebug.h"
```
Comment (philburk) [inline samples/MegaDrone/src/main/cpp/Synth.h]: Still needed?

**Comment by atneya** [comment]
Using a const ptr is a little bit messy because of the need to initialize prior to the constructor. If it is clearer, we can use a non-const pointer and have it instantiated as before.

File: samples/MegaDrone/src/main/cpp/Synth.h (hunk 2 above)
Comment (philburk) [reply samples/MegaDrone/src/main/cpp/Synth.h]: > Using a const ptr is a little bit messy because of the need to initialize prior to the constructor.
> If it is clearer, we can use a non-const pointer and have it instantiated as before.

I see what you mean. This is messy. Feel free to go back to the original.

Comment (atneya) [reply samples/MegaDrone/src/main/cpp/Synth.h]: Added in latest commit

**Comment by dturner** [comment]
Many thanks for fixing this.
