### PR TITLE
OboeTester: Add noise pulse for Tap to Tone

### LINKED ISSUE #2247: OboeTester: Use noise pulse instead of saw ping in tap to tone test
From initial testing, when playing a noise pulse instead of a sawtooth wave is much more consistent. I seem to never get a failed test with a noise pulse

### PR DESCRIPTION
**Pull request by robertwu1**
Fixes #2247

### CODE REVIEW

File: apps/OboeTester/app/src/main/cpp/jni-bridge.cpp [hunk 1]
```diff
@@ -994,6 +994,12 @@ Java_com_mobileer_oboetester_TestAudioActivity_setDefaultAudioValues(JNIEnv *env
     oboe::DefaultStreamValues::FramesPerBurst = audio_manager_frames_per_burst;
 }
 
+JNIEXPORT void JNICALL
+Java_com_mobileer_oboetester_TapToToneActivity_useNoisePulse(JNIEnv *env, jclass clazz,
+                                                                     jboolean enabled) {
```
Comment (flamme) [inline apps/OboeTester/app/src/main/cpp/jni-bridge.cpp]: nit, align with previous line.

File: apps/OboeTester/app/src/main/cpp/SawPingGenerator.cpp [hunk 2]
```diff
@@ -50,7 +51,7 @@ int32_t SawPingGenerator::onProcess(int numFrames) {
     // Check level to prevent numeric underflow.
     if (mLevel > 0.000001) {
         for (int i = 0; i < numFrames; i++) {
```
Comment (flamme) [inline apps/OboeTester/app/src/main/cpp/SawPingGenerator.cpp]: If noise is desired, isn't it better to use noise generator instead of changing the SawPingGenerator?

File: apps/OboeTester/app/src/main/cpp/jni-bridge.cpp (hunk 1 above)
Comment (robertwu1) [reply apps/OboeTester/app/src/main/cpp/jni-bridge.cpp]: Thanks! Done

File: apps/OboeTester/app/src/main/cpp/SawPingGenerator.cpp (hunk 2 above)
Comment (robertwu1) [reply apps/OboeTester/app/src/main/cpp/SawPingGenerator.cpp]: No, we want to send a signal that starts at 1.0 and gets multiplied by 0.999 every iteration. This gives us a clean signal that we don't accidentally double-count. This is still a saw ping and belongs in this class. It's just that we aren't playing at a note anymore.

Comment (flamme) [reply apps/OboeTester/app/src/main/cpp/SawPingGenerator.cpp]: As discussed offline, please make a new class for the noise generator and use it when noise is preferred.

Comment (robertwu1) [reply apps/OboeTester/app/src/main/cpp/SawPingGenerator.cpp]: Done

File: apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp [hunk 3]
```diff
@@ -677,11 +677,18 @@ void ActivityTapToTone::configureAfterOpen() {
     mSinkI32 = std::make_shared<SinkI32>(mChannelCount);
 
     std::shared_ptr<oboe::AudioStream> outputStream = getOutputStream();
-    sawPingGenerator.setSampleRate(outputStream->getSampleRate());
-    sawPingGenerator.frequency.setValue(FREQUENCY_SAW_PING);
-    sawPingGenerator.amplitude.setValue(AMPLITUDE_SAW_PING);
 
-    sawPingGenerator.output.connect(&(monoToMulti->input));
+    mNoisePulseGenerator.amplitude.setValue(AMPLITUDE_SAW_PING);
```
Comment (flamme) [inline apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp]: AMPLITUDE_NOISE_PULSE?

**Review by flamme — APPROVED** [review]
