### PR TITLE
oboe: add AudioStreamDataCallback and AudioStreamErrorCallback

### LINKED ISSUE #917: Add AudioStreamErrorCallback for better control over disconnect handling
The current design of the AudioStreamCallback with onErrorBeforeCLose() and onErrorAfterClose() is a problem. 
The stop and close is done inside Oboe in a thread spawned by the AAudio callback function.
The stop and close cannot be locked by the developer and may collide with similar actions taken by the app.
For example, when unplugging headphones, the error callback may be called causing a stop and close and a reopening of the stream.
At the same time the device menu may change causing the same activity. This was happening in Hello-Oboe and was causing a crash.

Perhaps we should add a separate error callback that has a single method. Oboe will not spawn a thread for this. Then the developer can lock around the stop/close and completely control the error response with locks, etc. They could also signal their own audio management thread. 

class AudioStreamErrorCallback {
    virtual void onError(AudioStream* /* oboeStream */, Result /* error */);
};

Then in the builder we could add:

AudioStreamBuilder *setErrorCallback(AudioStreamErrorCallback *streamErrorCallback);

In Oboe, if the new error callback is set then Oboe will call it and let the app handle the error completely.
If they do not set it then we do the old behavior. and stop/close the stream for them automatically in a separate thread.
This can be backwards compatible.

### PR DESCRIPTION
**Pull request by philburk**
This allows an app to use different callbacks for data processing
and error processing. The AudioStreamCallback inherits
from both interfaces.

There is also a new method: bool onError()
that allows an app to completely override the default
error handling.

This change is backwards compatible with older versions.

Fixes #917

### CODE REVIEW

File: apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp [hunk 1]
```diff
@@ -80,17 +80,18 @@ oboe::DataCallbackResult OboeStreamCallbackProxy::onAudioReady(
...
-    }
-}
-
-void OboeStreamCallbackProxy::onErrorAfterClose(oboe::AudioStream *audioStream, oboe::Result  error) {
-    LOGD("OboeStreamCallbackProxy::%s(%p, %d) called", __func__, audioStream, error);
-    if (mCallback != nullptr) {
-        mCallback->onErrorAfterClose(audioStream, error);
-    }
-}
+// FIXME
```
Comment (philburk) [inline apps/OboeTester/app/src/main/cpp/OboeStreamCallbackProxy.cpp:83]: remove dead code

File: include/oboe/AudioStreamBase.h [hunk 2]
```diff
@@ -148,9 +173,15 @@ class AudioStreamBase {
     }
 
 protected:
+    /** The callback which will be fired when new data is ready to be read/written. **/
+    AudioStreamDataCallback        *mDataCallback = nullptr;
+
+    /** The callback which will be fired when an error or a disconnect occurs. **/
+    AudioStreamErrorCallback       *mErrorCallback = nullptr;
+
+    /** The callback that combines data and error callback. **/
```
Comment (philburk) [inline include/oboe/AudioStreamBase.h:182]: remove dead code

File: include/oboe/AudioStreamCallback.h [hunk 3]
```diff
@@ -75,49 +76,106 @@ class AudioStreamCallback {
...
+    virtual ~AudioStreamErrorCallback() = default;
 
     /**
-     * This will be called when an error occurs on a stream or when the stream is disconnected.
+     * This will be called first when an error occurs on a stream or when the stream is disconnected.
+     *
+     * It can be used to override and customize the normal error processing.
+     * Use of this method is considered an advanced technique.
+     * It might, for example, be used if an app want to use a high level lock when
+     * closing and reopening  a stream.
```
Comment (philburk) [inline include/oboe/AudioStreamCallback.h:107]: two spaces

File: src/aaudio/AudioStreamAAudio.cpp [hunk 4]
```diff
@@ -101,14 +103,18 @@ bool AudioStreamAAudio::isSupported() {
...
+// We use a method so we can access protected methods on the stream.
 // Launch a thread to handle the error.
 // That other thread can safely stop, close and delete the stream.
 void AudioStreamAAudio::internalErrorCallback(
         AAudioStream *stream,
         void *userData,
         aaudio_result_t error) {
+    oboe::Result oboeResult = static_cast<Result>(error);
     AudioStreamAAudio *oboeStream = reinterpret_cast<AudioStreamAAudio*>(userData);
+    LOGI("%s() oboeResult = %d", __func__, oboeResult);
```
Comment (philburk) [inline src/aaudio/AudioStreamAAudio.cpp:116]: remove or LOGD

File: src/common/AudioSourceCaller.cpp [hunk 5]
```diff
@@ -20,7 +20,7 @@ using namespace oboe;
 using namespace flowgraph;
 
 int32_t AudioSourceCaller::onProcessFixedBlock(uint8_t *buffer, int32_t numBytes) {
-    oboe::AudioStreamCallback *callback = mStream->getCallback();
+    oboe::AudioStreamDataCallback *callback = mStream->getDataCallback();
```
Comment (philburk) [inline src/common/AudioSourceCaller.cpp:23]: oboe:: not needed

File: src/common/FilterAudioStream.cpp [hunk 6]
```diff
@@ -90,3 +91,17 @@ ResultWithValue<int32_t> FilterAudioStream::read(void *buffer,
...
+    if (oboeStream->getDirection() == Direction::Output) {
+        framesProcessed = mFlowGraph->read(audioData, numFrames, 0 /* timeout */);
+    } else {
+        framesProcessed = mFlowGraph->write(audioData, numFrames);
+    }
+    LOGI("%s() framesProcessed = %d, numFrames = %d", __func__, framesProcessed, numFrames);
+    return (framesProcessed < numFrames)
+           ? DataCallbackResult::Stop
+           : mFlowGraph->getDataCallbackResult();
+}
```
Comment (philburk) [inline src/common/FilterAudioStream.cpp:107]: add EOL

File: src/common/FilterAudioStream.cpp [hunk 7]
```diff
@@ -90,3 +91,17 @@ ResultWithValue<int32_t> FilterAudioStream::read(void *buffer,
...
+DataCallbackResult FilterAudioStream::onAudioReady(AudioStream *oboeStream,
+                                void *audioData,
+                                int32_t numFrames) {
+    int32_t framesProcessed;
+    if (oboeStream->getDirection() == Direction::Output) {
+        framesProcessed = mFlowGraph->read(audioData, numFrames, 0 /* timeout */);
+    } else {
+        framesProcessed = mFlowGraph->write(audioData, numFrames);
+    }
+    LOGI("%s() framesProcessed = %d, numFrames = %d", __func__, framesProcessed, numFrames);
```
Comment (philburk) [inline src/common/FilterAudioStream.cpp:103]: remove

File: src/common/FilterAudioStream.h [hunk 8]
```diff
@@ -42,8 +42,11 @@ class FilterAudioStream : public AudioStream, AudioStreamCallback {
     : AudioStream(builder)
     , mChildStream(childStream) {
         // Intercept the callback if used.
-        if (builder.getCallback() != nullptr) {
-            mStreamCallback = mChildStream->swapCallback(this);
+        if (builder.getErrorCallback() != nullptr) {
```
Comment (philburk) [inline src/common/FilterAudioStream.h:45]: use isErrorCallbackSpecified()

File: src/common/FilterAudioStream.h [hunk 9]
```diff
@@ -42,8 +42,11 @@ class FilterAudioStream : public AudioStream, AudioStreamCallback {
...
+            mErrorCallback = mChildStream->swapErrorCallback(this);
+        }
+        if (builder.getDataCallback() != nullptr) {
```
Comment (philburk) [inline src/common/FilterAudioStream.h:48]: use isDataCallbackSpecified()

**Comment by mgood7123** [comment]
when is this going to be merged? looks like it has been sitting for 6 days

File: include/oboe/AudioStreamCallback.h [hunk 10]
```diff
@@ -75,49 +76,106 @@ class AudioStreamCallback {
...
+     *
+     * It can be used to override and customize the normal error processing.
+     * Use of this method is considered an advanced technique.
+     * It might, for example, be used if an app want to use a high level lock when
+     * closing and reopening a stream.
+     * Or it might be used when an app want to signal a management thread that handles
+     * all of the stream state.
+     *
+     * If this method returns false then
+     * the stream will be stopped, and onErrorBeforeClose() will be called,
```
Comment (dturner) [inline include/oboe/AudioStreamCallback.h:112]:
```suggestion
     * the stream will be stopped by Oboe in the following way: onErrorBeforeClose() will be called,
```

File: include/oboe/AudioStreamCallback.h [hunk 11]
```diff
@@ -75,49 +76,106 @@ class AudioStreamCallback {
...
+     * then the stream will be closed and onErrorAfterClose() will be closed.
      *
-     * Note that this will be called on a different thread than the onAudioReady() thread.
-     * This thread will be created by Oboe.
+     * If this method returns true then the normal error processing will not occur.
+     * In that case, the app MUST stop() and close() the stream!
+     *
+     * Note that this will be called on a thread created by Oboe.
```
Comment (dturner) [inline include/oboe/AudioStreamCallback.h:118]:
```suggestion
     * Note that this method will be called on a thread created by Oboe.
```

File: include/oboe/AudioStreamCallback.h [hunk 12]
```diff
@@ -75,49 +76,106 @@ class AudioStreamCallback {
...
+     *
+     * @param audioStream pointer to the associated stream
+     * @param error
+     */
+    virtual bool onError(AudioStream* /* audioStream */, Result /* error */) {
+        return false; // false means the stream will be stopped and closed by Oboe
+        // return true; // true means the stream will be stopped and closed by the app
```
Comment (dturner) [inline include/oboe/AudioStreamCallback.h:125]: There's some redundancy in the comments here. Consider consolidating this into the `@return` comment or removing this comment and the one above altogether.

File: include/oboe/AudioStreamCallback.h [hunk 13]
```diff
@@ -75,49 +76,106 @@ class AudioStreamCallback {
...
+    }
+
+    /**
+     * This will be called when an error occurs on a stream or when the stream is disconnected
+     * and if onError() returns false.
```
Comment (dturner) [inline include/oboe/AudioStreamCallback.h:130]:
```suggestion
     * and if onError() returns false (indicating that the error has not already been handled).
```

File: include/oboe/AudioStreamCallback.h [hunk 14]
```diff
@@ -75,49 +76,106 @@ class AudioStreamCallback {
...
+     * @param audioStream pointer to the associated stream
      * @param error
      */
-    virtual void onErrorBeforeClose(AudioStream* /* oboeStream */, Result /* error */) {}
+    virtual void onErrorBeforeClose(AudioStream* /* audioStream */, Result /* error */) {}
 
     /**
-     * This will be called when an error occurs on a stream or when the stream is disconnected.
+     * This will be called when an error occurs on a stream or when the stream is disconnected
+     * and if onError() returns false.
```
Comment (dturner) [inline include/oboe/AudioStreamCallback.h:147]:
```suggestion
     * and if onError() returns false (indicating that the error has not already been handled).
```

File: include/oboe/AudioStreamCallback.h [hunk 15]
```diff
@@ -75,49 +76,106 @@ class AudioStreamCallback {
...
+/**
+ * AudioStreamCallback defines a callback interface for:
+ *
+ * 1) moving data to/from an audio stream using `onAudioReady`
+ * 2) being alerted when a stream has an error using `onError*` methods
+ *
+ * It is used with AudioStreamBuilder::setCallback().
+ *
+ * It combines the interfaces defined by AudioStreamDataCallback and AudioStreamErrorCallback.
+ * This was the original callback object. We now recommend using the individual interfaces.
```
Comment (dturner) [inline include/oboe/AudioStreamCallback.h:171]:
```suggestion
 * This was the original callback object. We now recommend using the individual interfaces
 * and using setDataCallback() and setErrorCallback().
```

File: src/aaudio/AudioStreamAAudio.cpp [hunk 16]
```diff
@@ -62,14 +62,16 @@ static aaudio_data_callback_result_t oboe_aaudio_data_callback_proc(
...
     LOGD("%s() - entering >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>", __func__);
-    oboeStream->requestStop();
-    if (oboeStream->getCallback() != nullptr) {
-        oboeStream->getCallback()->onErrorBeforeClose(oboeStream, error);
-    }
-    oboeStream->close();
-    if (oboeStream->getCallback() != nullptr) {
+    AudioStreamErrorCallback *errorCallback = oboeStream->getErrorCallback();
+    if (errorCallback == nullptr) return; // should be impossible
+    bool handled = errorCallback->onError(oboeStream, error);
```
Comment (dturner) [inline src/aaudio/AudioStreamAAudio.cpp:67]:
```suggestion
    bool isErrorHandled = errorCallback->onError(oboeStream, error);
```

File: src/aaudio/AudioStreamAAudio.cpp [hunk 17]
```diff
@@ -62,14 +62,16 @@ static aaudio_data_callback_result_t oboe_aaudio_data_callback_proc(
...
+
+    if (!handled) {
```
Comment (dturner) [inline src/aaudio/AudioStreamAAudio.cpp:69]:
```suggestion
    if (!isErrorHandled) {
```

File: src/aaudio/AudioStreamAAudio.cpp [hunk 18]
```diff
@@ -118,16 +123,14 @@ void AudioStreamAAudio::internalErrorCallback(
     if (oboeStream->wasErrorCallbackCalled()) { // block extra error callbacks
         LOGE("%s() multiple error callbacks called!", __func__);
     } else if (stream != oboeStream->getUnderlyingStream()) {
-        LOGW("%s() stream already closed or closing", __func__); // can happen if there are bugs
+        LOGW("%s() stream already closed or closing", __func__); // might happen if there are bugs
```
Comment (dturner) [inline src/aaudio/AudioStreamAAudio.cpp:126]: The comment is a bit vague. Under what circumstances could this happen? Can we link to specific gh issues?

**Review by dturner — CHANGES_REQUESTED** [review]
Great change, thanks very much for doing this. Few minor things but LGTM. 

I will make the changes to our samples in a follow up PR.

File: include/oboe/AudioStreamCallback.h [hunk 19]
```diff
@@ -75,49 +76,106 @@ class AudioStreamCallback {
...
      */
     virtual DataCallbackResult onAudioReady(
-            AudioStream *oboeStream,
+            AudioStream *audioStream,
             void *audioData,
             int32_t numFrames) = 0;
+};
+
+/**
+ * AudioStreamDataCallback defines a callback interface for
```
Comment (dturner) [inline include/oboe/AudioStreamCallback.h:91]:
```suggestion
 * AudioStreamErrorCallback defines a callback interface for
```

File: include/oboe/AudioStreamBuilder.h [hunk 20]
```diff
@@ -305,9 +305,45 @@ class AudioStreamBuilder : public AudioStreamBase {
...
+    /**
+     * Specifies an object to handle data related callbacks from the underlying API.
+     *
+     * <strong>Important: See AudioStreamCallback for restrictions on what may be called
+     * from the callback methods.</strong>
+     *
+     * @param dataCallback
+     * @return pointer to the builder so calls can be chained
+     */
+    AudioStreamBuilder *setDataCallback(oboe::AudioStreamDataCallback *dataCallback) {
```
Comment (dturner) [inline include/oboe/AudioStreamBuilder.h:317]: Random thought. For both the data and error callbacks the most common use case is that you just implement `onAudioReady` and `onErrorAfterClose`. I wonder if we should overload `setDataCallback` to take a lambda of type: `AudioCallbackResult(AudioStream *, void *, int)`. This would enable you to supply a callback function, rather than a whole class. Same for `setErrorCallback`.

File: include/oboe/AudioStreamCallback.h (hunk 12 above)
Comment (philburk) [reply include/oboe/AudioStreamCallback.h:125]: OK, will do in a subsequent patch.

File: src/aaudio/AudioStreamAAudio.cpp [hunk 21]
```diff
@@ -62,14 +62,16 @@ static aaudio_data_callback_result_t oboe_aaudio_data_callback_proc(
...
                                           Result error) {
     LOGD("%s() - entering >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>", __func__);
-    oboeStream->requestStop();
-    if (oboeStream->getCallback() != nullptr) {
-        oboeStream->getCallback()->onErrorBeforeClose(oboeStream, error);
-    }
-    oboeStream->close();
-    if (oboeStream->getCallback() != nullptr) {
+    AudioStreamErrorCallback *errorCallback = oboeStream->getErrorCallback();
+    if (errorCallback == nullptr) return; // should be impossible
```
[the remark this answers is not in the document]
Comment (philburk) [reply src/aaudio/AudioStreamAAudio.cpp:66]: Will do in a subsequent commit.

File: src/aaudio/AudioStreamAAudio.cpp (hunk 18 above)
Comment (philburk) [reply src/aaudio/AudioStreamAAudio.cpp:126]: I don't know of any bugs that cause this. But if it happened then it would be a bug.

File: include/oboe/AudioStreamBuilder.h (hunk 20 above)
Comment (philburk) [reply include/oboe/AudioStreamBuilder.h:317]: Good idea for a subsequent patch.

File: include/oboe/AudioStreamCallback.h (hunk 14 above)
Comment (philburk) [reply include/oboe/AudioStreamCallback.h]: suggestion merged
