### PR TITLE
OboeTester: Data Paths cleanup, remove earpiece

### LINKED ISSUE #1866: Cleanup Data Paths test
When a stream cannot open, it does not say whether it is the input or output stream.

The Earpiece consistently cannot be heard. Too quiet.

InputPreset:VoiceCommunication - The AEC messes with the signal so much the test just fails on some devices.

See [b/283836117](http://b/283836117) | P1 | CTS Verifier Data Paths Earpiece and VoiceCommunication test failing

### PR DESCRIPTION
**Pull request by philburk**
Remove earpiece tests because they are flakey.
Show more info when open fails.
Display channel masks in hex format.

Fixes #1866

### CODE REVIEW

File: apps/OboeTester/app/src/main/java/com/mobileer/audio_device/AudioDeviceInfoConverter.java [hunk 1]
```diff
@@ -116,6 +116,21 @@ private static String intArrayToString(int[] integerArray){
...
+     * Converts an integer array into a hexadecimal string where each int is separated by a space
+     *
+     * @param integerArray the integer array to convert to a string
+     * @return string containing all the integer values separated by spaces
+     */
+    private static String intArrayToStringHex(int[] integerArray){
+        StringBuilder sb = new StringBuilder();
+        for (int i = 0; i < integerArray.length; i++){
+            sb.append(String.format("0x%02X", integerArray[i]));
+            if (i != integerArray.length -1) sb.append(" ");
```
Comment (robertwu1) [inline apps/OboeTester/app/src/main/java/com/mobileer/audio_device/AudioDeviceInfoConverter.java:129]: nit: integerArray.length - 1

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java [hunk 2]
```diff
@@ -70,10 +70,12 @@ public class TestDataPathsActivity  extends BaseAutoGlitchActivity {
...
 
-    public static final int JAVA_CHANNEL_IN_LEFT = 1 << 2;
-    public static final int JAVA_CHANNEL_IN_RIGHT = 1 << 3;
-    public static final int JAVA_CHANNEL_IN_FRONT = 1 << 4;
-    public static final int JAVA_CHANNEL_IN_BACK = 1 << 5;
+    // These define the values returned by the Java API deviceInfo.getChannelMasks().
+    public static final int JAVA_CHANNEL_IN_LEFT = 1 << 2;  // AudioFormat.CHANNEL_IN_LEFT
+    public static final int JAVA_CHANNEL_IN_RIGHT = 1 << 3; // AudioFormat.CHANNEL_IN_RIGHT
+    public static final int JAVA_CHANNEL_IN_FRONT = 1 << 4; // AudioFormat.CHANNEL_IN_FRONT
+    public static final int JAVA_CHANNEL_IN_BACK = 1 << 5;  // AudioFormat.CHANNEL_IN_BACK
```
Comment (robertwu1) [inline apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:77]: can you also add comments to JAVA_CHANNEL_IN_BACK_LEFT and the others below?

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java [hunk 3]
```diff
@@ -734,7 +724,7 @@ void testOutputDevices() throws InterruptedException {
                     }
                 }
             } else {
-                log("Device skipped. Not BuiltIn Speaker.");
+                log("Device skipped because DeviceType not testable.");
```
Comment (robertwu1) [inline apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestDataPathsActivity.java:727]: nit: is not testable

**Review by robertwu1 — APPROVED** [review]
