### PR TITLE
Samples: Remove some fixed size constants

### LINKED ISSUE #1921: Potential buffer overflows with some hard coded constants in samples
In samples/shared/Mixer.h:

~~~
constexpr int32_t kBufferSize = 192*10;  // Temporary buffer is used for mixing
constexpr uint8_t kMaxTracks = 100;
~~~

### PR DESCRIPTION
**Pull request by robertwu1**
This PR fixes some issues with potential overflow of buffers.
1. Mixer buffer in Mixer.h could be too small if frame size is large. Fix here is to use std::unique_ptr<float[]> instead of a raw array. Mixer.h is used by MegaDrone, Soundboard, and RhythmGame.
2. If the number of tracks goes over 100 in Mixer.h, there will be a buffer overflow. Fix here is to use std::vector<IRenderableAudio*> instead of an std::array.
3. If the number of tracks goes over 100 in Synth.h, there will be a buffer overflow. Fix here is to use std::unique_ptr<SynthSound[]> instead of an std::array.

Fixes #1921

### CODE REVIEW

File: samples/shared/Mixer.h [hunk 1]
```diff
@@ -34,35 +31,38 @@ class Mixer : public IRenderableAudio {
 public:
     void renderAudio(float *audioData, int32_t numFrames) {
 
+        int numBytes = numFrames * mChannelCount;
```
Comment (philburk) [inline samples/shared/Mixer.h:34]: numBytes should be "numSamples" or "numFloats"

Comment (robertwu1) [reply samples/shared/Mixer.h]: Oops... Thanks! I just fixed it

**Review by philburk — APPROVED** [review]
