### PR TITLE
resampler fix glitch in some configurations

### LINKED ISSUE #1622: Glitches in audio when SRate is 11025 and SRC Best is selected
Android version(s): S, T
Android device(s): all?
Oboe version: 1.5+
App name used for testing:  OboeTester
 
**Short description**
Track internal bug [b/245513523](http://b/245513523)

**Steps to reproduce**
1. Install Oboe Tester app (apk version: 2.3.0) on DUT
1. Open oboe tester app
1. Select Test Output from menu
1. Select SRate - 11025
1. Select SRC : Best
1. Tap on OPEN
1. Tap on START and observe
 
**Expected behavior**
Clean sine wave.

**Actual behavior**
Distorted sound.

### PR DESCRIPTION
**Pull request by philburk**
Converting from 11025 to 48000 with Best quality had a strong glitch. Added guard row to Coefficients table for interpolation.

Fixes #1622

### CODE REVIEW

File: src/flowgraph/resampler/SincResampler.cpp [hunk 1]
```diff
@@ -63,7 +56,7 @@ void SincResampler::readFrame(float *frame) {
         float coefficient2 = *coefficients2++;
         for (int channel = 0; channel < getChannelCount(); channel++) {
             float sample = *xFrame++;
-            mSingleFrame[channel] +=  sample * coefficient1;
+            mSingleFrame[channel]  += sample * coefficient1;
```
Comment (robertwu1) [inline src/flowgraph/resampler/SincResampler.cpp:59]: extra space

File: src/flowgraph/resampler/SincResampler.cpp [hunk 2]
```diff
@@ -42,16 +43,8 @@ void SincResampler::readFrame(float *frame) {
     // Determine indices into coefficients table.
     double tablePhase = getIntegerPhase() * mPhaseScaler;
     int index1 = static_cast<int>(floor(tablePhase));
```
Comment (robertwu1) [inline src/flowgraph/resampler/SincResampler.cpp:45]: Can we use more descriptive names for index1 and index2?

File: tests/testResampler.cpp [hunk 3]
```diff
@@ -0,0 +1,168 @@
...
+
+#include <gtest/gtest.h>
+#include <oboe/Oboe.h>
+
+#include "flowgraph/resampler/MultiChannelResampler.h"
+
+using namespace oboe::resampler;
+
+// Measure zero crossings.
+static int32_t countZeroCrossingsWithHysteresis(float *input, int32_t numSamples) {
```
Comment (robertwu1) [inline tests/testResampler.cpp:32]: This function doesn't seem symmetric with respect to 0 for the first time you run this. If you first go from 0 to 0.5, you increment zeroCrossingCount. However, if you first go from 0 to -0.5, this does not increment zeroCrossingCount.

File: tests/testResampler.cpp [hunk 4]
```diff
@@ -0,0 +1,168 @@
...
+
+#if 0
+    // Save to disk for inspection.
+    FILE *fp = fopen( "/sdcard/Download/src_float_out.raw" , "wb" );
+    fwrite(outputBuffer.get(), sizeof(float), numRead, fp );
+    fclose(fp);
+#endif
+}
+
+TEST(test_resampler, resampler_8000_48000_best) {
```
Comment (robertwu1) [inline tests/testResampler.cpp:122]: Can you run the test cases for all potential sample rate conversions? If there are too many cases and it takes too long to run, can you at least run this locally as a sanity check?

File: tests/testResampler.cpp [hunk 5]
```diff
@@ -0,0 +1,214 @@
...
+    const int kNumOutputSamples = 10000;
+    const double framesPerCycle = 81.379; // target output period
+
+    int numInputSamples = kNumOutputSamples * sourceRate / sinkRate;
+
+    std::unique_ptr<float[]>  inputBuffer = std::make_unique<float[]>(numInputSamples);
+    std::unique_ptr<float[]>  outputBuffer = std::make_unique<float[]>(kNumOutputSamples);
+
+    // Generate a sine wave for input.
+    const double kPhaseIncrement =  2.0 * sinkRate / (framesPerCycle * sourceRate);
```
Comment (robertwu1) [inline tests/testResampler.cpp:69]: extra space

File: tests/testResampler.cpp [hunk 6]
```diff
@@ -0,0 +1,214 @@
...
+    double phase = 0.0;
+    for (int i = 0; i < numInputSamples; i++) {
+        inputBuffer[i] = sin(phase * M_PI);
+        phase += kPhaseIncrement;
+        if (phase > 1.0) phase -= 2.0;
```
Comment (robertwu1) [inline tests/testResampler.cpp:74]: Can the phase go over 3.0 for some extreme situations?

File: tests/testResampler.cpp [hunk 7]
```diff
@@ -0,0 +1,214 @@
...
+    mcResampler.reset(MultiChannelResampler::make(kChannelCount,
+                                                 sourceRate,
+                                                 sinkRate,
+                                                 quality));
+    int inputFramesLeft = numInputSamples;
+    int numRead = 0;
+    float *input = inputBuffer.get(); // for iteration
+    float *output = outputBuffer.get();
+    while (inputFramesLeft > 0) {
+        if(mcResampler->isWriteNeeded()) {
```
Comment (robertwu1) [inline tests/testResampler.cpp:89]: space after if

File: tests/testResampler.cpp [hunk 8]
```diff
@@ -0,0 +1,214 @@
...
+            inputFramesLeft--;
+        } else {
+            mcResampler->readNextFrame(output);
+            output++;
+            numRead++;
+        }
+    }
+
+    ASSERT_LE(numRead, kNumOutputSamples);
+    EXPECT_GT(numRead, kNumOutputSamples - 16);
```
Comment (robertwu1) [inline tests/testResampler.cpp:101]: Where is this 16 from?

**Review by robertwu1 — APPROVED** [review]
