### PR TITLE
oboe: add quirk for S20 input

### LINKED ISSUE #892: LiveEffect demo corrupt audio with internal mic and speakers on Samsung S20 Ultra 5G
Android version(s): 10
Android device(s): Samsung S20 Ultra 5G
Oboe version: master
App name used for testing: LiveEffect
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 
**Short description**
Select built-in microphone and built-in earphone speaker. Audio sounds corrupted, like a deep rumbling. On Pixel 2 XL, the same test (built-in microphone and built-in earphone speaker) sounds crystal clear.

**Steps to reproduce**
Load LiveEffect, select bult-in microphone, built-in earphone speaker
Select aaudio or OpenSL ES (happens on both)
Hold phone to ear and talk

**Expected behavior**
audio should be clear

**Actual behavior**
audio is not clear

**Any additional context**

### PR DESCRIPTION
**Pull request by philburk**
The S20 input had some glitches in an early version.
So we turn off MMAP in that case.

We also moved the AAudioExtensions class from OboeTester into Oboe.

Fixes #892

### CODE REVIEW

File: src/aaudio/AAudioExtensions.h [hunk 1]
```diff
@@ -20,6 +20,15 @@
 #include <dlfcn.h>
 #include <stdint.h>
 
+#include <sys/system_properties.h>
+
+#include "common/OboeDebug.h"
+#include "oboe/Oboe.h"
+#include "AAudioLoader.h"
+
+
```
Comment (philburk) [inline src/aaudio/AAudioExtensions.h:29]: extra line

File: src/aaudio/AAudioExtensions.h [hunk 2]
```diff
@@ -50,20 +59,24 @@ class AAudioExtensions {
...
+        if (open()) return false;
+        if (mAAudioStream_isMMap == nullptr) return false;
         return mAAudioStream_isMMap(aaudioStream);
     }
 
-    bool setMMapEnabled(bool enabled) {
-        if (!loadLibrary()) return false;
+    int32_t setMMapEnabled(bool enabled) {
+        if (open()) return -1;
         if (mAAudio_setMMapPolicy == nullptr) return false;
```
Comment (philburk) [inline src/aaudio/AAudioExtensions.h:74]: return -1

File: src/aaudio/AAudioExtensions.h [hunk 3]
```diff
@@ -50,20 +59,24 @@ class AAudioExtensions {
...
+
+    bool isMMapUsed(AAudioStream *aaudioStream) {
+        if (open()) return false;
+        if (mAAudioStream_isMMap == nullptr) return false;
         return mAAudioStream_isMMap(aaudioStream);
     }
 
-    bool setMMapEnabled(bool enabled) {
-        if (!loadLibrary()) return false;
+    int32_t setMMapEnabled(bool enabled) {
```
Comment (philburk) [inline src/aaudio/AAudioExtensions.h:72]: Should be aaudio_result_t

File: src/common/AudioStreamBuilder.cpp [hunk 4]
```diff
@@ -156,7 +157,15 @@ Result AudioStreamBuilder::openStream(AudioStream **streamPP) {
         }
     }
 
-    result = streamP->open(); // TODO review API
+    bool isMMapEnabled = AAudioExtensions::getInstance().isMMapEnabled();
```
Comment (philburk) [inline src/common/AudioStreamBuilder.cpp:160]: Add comment

File: src/aaudio/AAudioExtensions.h (hunk 3 above)
Comment (philburk) [reply src/aaudio/AAudioExtensions.h:72]: keep aaudio_result_t internal

File: src/aaudio/AAudioExtensions.h [hunk 5]
```diff
@@ -95,47 +109,56 @@ class AAudioExtensions {
...
-                return false;
-            }
+    /**
+     * Load the function pointers.
+     * This can be called multiple times.
+     * It should only be called from one thread.
+     *
+     * @return 0 if successful or negative error.
+     */
+    aaudio_result_t open() {
```
Comment (dturner) [inline src/aaudio/AAudioExtensions.h:119]: Could we make this method a bit more self-explanatory, maybe `openLibrary` or `loadSymbols`?

File: src/common/AudioStreamBuilder.cpp [hunk 6]
```diff
@@ -156,7 +157,20 @@ Result AudioStreamBuilder::openStream(AudioStream **streamPP) {
...
 
-    result = streamP->open(); // TODO review API
+    // If MMAP has a problem in this case then disable it temporarily.
+    bool wasMMapOriginallyEnabled = AAudioExtensions::getInstance().isMMapEnabled();
+    bool wasMMapTemporarilyDisabled = false;
+    if (wasMMapOriginallyEnabled) {
+        bool isMMapSafe = QuirksManager::getInstance().isMMapSafe(childBuilder);
+        if (!isMMapSafe) {
+            AAudioExtensions::getInstance().setMMapEnabled(false);
+            wasMMapTemporarilyDisabled = true;
```
Comment (dturner) [inline src/common/AudioStreamBuilder.cpp:167]: We only re-enabled MMap if `isMMapSafe` == false - is that right? I feel like there's either an error, or some context around this quirk which I'm missing.

Comment (philburk) [reply src/common/AudioStreamBuilder.cpp:167]: The code should disable MMAP if it is not safe in this situation.

Is there a better word than "safe"? Maybe "WorkingProperly" or "OK"?

File: src/aaudio/AAudioExtensions.h (hunk 5 above)
Comment (philburk) [reply src/aaudio/AAudioExtensions.h]: loadSymbols() DONE

File: src/common/AudioStreamBuilder.cpp (hunk 6 above)
Comment (philburk) [reply src/common/AudioStreamBuilder.cpp:167]: MMAPEnabled only has effect during the open call! That was probably not clear.

Comment (philburk) [reply src/common/AudioStreamBuilder.cpp:167]: I added a comment.
