### PR TITLE
oboe: change default buffer sizes for INPUT

### LINKED ISSUE #655: Do not setBufferSizeInFrames for INPUT to 2
**Steps To Reproduce**
Open an input stream.
Call getBufferSizeInFrames()

**Expected behavior**
size close to capacity

**Actual behavior**
size == two bursts

**Additional context**
Set in AudioStreamBuilder.cpp. 

This can cause unnecessary XRuns.

### PR DESCRIPTION
**Pull request by philburk**
Fixes #655
Bump Oboe version to 1.2.1

### CODE REVIEW

File: src/common/AudioStreamBuilder.cpp [hunk 1]
```diff
@@ -149,17 +149,26 @@ Result AudioStreamBuilder::openStream(AudioStream **streamPP) {
...
-            int32_t optimalBufferSize = streamP->getFramesPerBurst() *
-                                        kBufferSizeInBurstsForLowLatencyStreams;
+        int32_t  optimalBufferSize = -1;
+        // Use a reasonable default buffer size.
+        if (streamP->getDirection() == Direction::Input) {
+            // For input, small size does not improve latency because the stream is usually
+            // run close to empty. And a low size can result in XRuns so always use the maximum.
+            optimalBufferSize = streamP->getBufferCapacityInFrames();
+        } else if (streamP->getPerformanceMode() == PerformanceMode::LowLatency
+                && streamP->getDirection() == Direction::Output)  { // // output check is redundant
```
Comment (philburk) [inline src/common/AudioStreamBuilder.cpp]: redundant //
