### PR TITLE
tests: sleep between close and open

### LINKED ISSUE #425: Flaky test: StreamStates.InputStreamLeftRunningShouldNotInterfereWithNextOpen
This test often fails when running on the emulator. Let's discuss during next meeting.

### PR DESCRIPTION
**Pull request by philburk**
This is to prevent a race condition on the emulator from
causing some tests to fail.

Fixes #425

### CODE REVIEW

File: tests/testStreamStates.cpp [hunk 1]
```diff
@@ -19,6 +19,10 @@
 
 using namespace oboe;
 
+// Sleep between close and open to avoid a race condition inside Android Audio.
+// On a Pixel 2 emulator on a fast Linux host, the minimum value is around 16 msec.
+#define OBOE_CLOSE_OPEN_SLEEP_MSEC  100
```
Comment (dturner) [inline tests/testStreamStates.cpp]: change to `constexpr`
