### PR TITLE
Synchronization for starting and stoping foreground service.

### LINKED ISSUE #2296: Foreground service may be stopped when running automation test in OboeTester
Currently, OboeTester starts foreground service in TestAudioActivity.onStart and stop it in onStop or onDestroy depending on if background operation is enabled or not. That can result in a unexpected foreground service stopped when running automation test. Imagine OboeTester is originally opened and in any of the test and then start automation test using adb shell. That will result in current activity stopped and then relaunching main activity and then the requested test activity. In this case, onPause will be called for the old activity, a new activity will be created, onStart will be called for the new activity, foreground service is started here. But in a short time, onStop and onDestroy will be called on the old activity. This will result in the foreground service stopped.

```
08-19 16:37:28.377  1500  5797 I wm_finish_activity: [0,13094926,87,com.mobileer.oboetester/.TestOutputActivity,clear-task-stack]
08-19 16:37:28.379  1500  5797 I wm_pause_activity: [0,13094926,com.mobileer.oboetester/.TestOutputActivity,userLeaving=false,finish]
08-19 16:37:28.382  1500  5797 I wm_new_intent: [0,83438867,87,com.mobileer.oboetester/.MainActivity,NULL,NULL,NULL,268435456]
08-19 16:37:28.383  1500  5797 I wm_task_moved: [87,87,0,1,2]
08-19 16:37:28.390 22782 22782 I wm_on_top_resumed_lost_called: [13094926,com.mobileer.oboetester.TestOutputActivity,pausing]
08-19 16:37:28.391 22782 22782 I wm_on_paused_called: [13094926,com.mobileer.oboetester.TestOutputActivity,performPause,1]
08-19 16:37:28.393  1500 10030 I wm_add_to_stopping: [0,13094926,com.mobileer.oboetester/.TestOutputActivity,completeFinishing]
08-19 16:37:28.397  1500 10030 I wm_set_resumed_activity: [0,com.mobileer.oboetester/.MainActivity,resumeTopActivity - onActivityStateChanged]
08-19 16:37:28.398  1500 10030 I wm_resume_activity: [0,83438867,87,com.mobileer.oboetester/.MainActivity]
08-19 16:37:28.404 22782 22782 I wm_on_restart_called: [83438867,com.mobileer.oboetester.MainActivity,performRestart,0]
08-19 16:37:28.404 22782 22782 I wm_on_start_called: [83438867,com.mobileer.oboetester.MainActivity,handleStartActivity,1]
08-19 16:37:28.411  1500  2711 I wm_task_moved: [87,87,0,1,2]
08-19 16:37:28.412  1500  2711 I wm_create_activity: [0,67887048,87,com.mobileer.oboetester/.TestOutputActivity,NULL,NULL,NULL,0]
08-19 16:37:28.412  1500  2711 I wm_pause_activity: [0,83438867,com.mobileer.oboetester/.MainActivity,userLeaving=true,resumeTopActivity]
08-19 16:37:28.415 22782 22782 I wm_on_resume_called: [83438867,com.mobileer.oboetester.MainActivity,RESUME_ACTIVITY,10]
08-19 16:37:28.416 22782 22782 I wm_on_top_resumed_gained_called: [83438867,com.mobileer.oboetester.MainActivity,topStateChangedWhenResumed]
08-19 16:37:28.422 22782 22782 I wm_on_top_resumed_lost_called: [83438867,com.mobileer.oboetester.MainActivity,topStateChangedWhenResumed]
08-19 16:37:28.422 22782 22782 I wm_on_paused_called: [83438867,com.mobileer.oboetester.MainActivity,performPause,0]
08-19 16:37:28.423  1500  2711 I wm_add_to_stopping: [0,83438867,com.mobileer.oboetester/.MainActivity,makeInvisible]
08-19 16:37:28.424  1500  2711 I wm_restart_activity: [0,67887048,87,com.mobileer.oboetester/.TestOutputActivity]
08-19 16:37:28.425  1500  2711 I wm_set_resumed_activity: [0,com.mobileer.oboetester/.TestOutputActivity,realStartActivityLocked - onActivityStateChanged]
08-19 16:37:28.460 22782 22782 I wm_on_create_called: [67887048,com.mobileer.oboetester.TestOutputActivity,performCreate,30]
08-19 16:37:28.462 22782 22782 I wm_on_start_called: [67887048,com.mobileer.oboetester.TestOutputActivity,handleStartActivity,2]
08-19 16:37:28.462 22782 22782 I wm_on_resume_called: [67887048,com.mobileer.oboetester.TestOutputActivity,RESUME_ACTIVITY,0]
08-19 16:37:28.465 22782 22782 I wm_on_top_resumed_gained_called: [67887048,com.mobileer.oboetester.TestOutputActivity,topStateChangedWhenResumed]
08-19 16:37:28.520  1500  1712 I wm_activity_launch_time: [0,67887048,com.mobileer.oboetester/.TestOutputActivity,112]
08-19 16:37:29.007  1500  1718 I wm_destroy_activity: [0,13094926,87,com.mobileer.oboetester/.TestOutputActivity,finish-imm:idle]
08-19 16:37:29.007  1500  1718 I wm_stop_activity: [0,83438867,com.mobileer.oboetester/.MainActivity]
08-19 16:37:29.025 22782 22782 I wm_on_stop_called: [13094926,com.mobileer.oboetester.TestOutputActivity,LIFECYCLER_STOP_ACTIVITY,2]
08-19 16:37:29.030 22782 22782 I wm_on_destroy_called: [13094926,com.mobileer.oboetester.TestOutputActivity,performDestroy,5]
08-19 16:37:29.039 22782 22782 I wm_on_stop_called: [83438867,com.mobileer.oboetester.MainActivity,STOP_ACTIVITY_ITEM,0]
```

### PR DESCRIPTION
**Pull request by flamme**
Fixes #2296.

### CODE REVIEW

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioForegroundService.java [hunk 1]
```diff
@@ -65,15 +71,31 @@ public int onStartCommand(Intent intent, int flags, int startId) {
                 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                     int serviceTypes = intent.getIntExtra("service_types", 0);
                     Log.i(TAG, "ServiceTypes: " + serviceTypes);
-                    startForeground(1, buildNotification(), serviceTypes);
+                    long activityId = intent.getLongExtra(KEY_ACTIVITY_ID, 0);
+                    synchronized (mActivityIds) {
+                        mActivityIds.add(activityId);
+                        if (mActivityIds.size() == 1 || serviceTypes != mServiceType) {
+                            startForeground(1, buildNotification(), serviceTypes);
```
Comment (robertwu1) [inline apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioForegroundService.java:78]: Take a look at https://github.com/google/oboe/pull/2106 for context on adding service types

What happens when you call startForegroundService on the new service type without stopping the old one?

Comment (flamme) [reply apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioForegroundService.java:78]: See line 77, the foreground service will be started with the new service type.

Comment (robertwu1) [reply apps/OboeTester/app/src/main/java/com/mobileer/oboetester/AudioForegroundService.java:78]: Gemini says:

If you call startForegroundService() multiple times with different Intent extras, each call will deliver the new Intent to the onStartCommand() method of the already running service. This allows you to update the service's state or pass new data without creating a new service instance.

I think we're good. LGTM!
