### PR TITLE
OboeTester: write WAV chunk sizes when recording

### LINKED ISSUE #2108: Invalid RIFF header chunksize and data chunksize size in recorded wav file
Android version(s): any
Android device(s): any
Oboe version: 1.9.0
App name used for testing: OboeTester
 
**Short description**
I am using `NativeAudioContext.cpp#saveWaveFile()` to record and save wav audio file. The recorded file cannot not be played back using Android's `MediaPlayer` because data and RIFF chunksize placeholder values `INT32_MAX`, assigned in `writeDataChunkHeader()` and `writeRiffHeader()`, are not updated after recording is completed. I was hoping `writer.close();` would do it, but that method is empty.

I was able to get the wav file playing by replacing `writeIntLittle(INT32_MAX)` in `writeRiffHeader()` and `writeDataChunkHeader()` with variables whose values are set once recording is stopped:
```
auto dataSize = mRecording->getSizeInFrames() * channelCount * bytesPerSample;
writer.setRiffChunkSize(dataSize + 36);
writer.setDataSize(dataSize);
```

**Steps to reproduce**
1. Open  OboeTester app and click "RECORD AND PLAY" -> RECORD -> STOP -> SHARE (to create wav file)
2. Open the wav file using https://hexed.it and observe two instances of `FF FF FF 7F`
3. Or, try playing this wav file using MediaPlayer or YTMusic and observe errors

### PR DESCRIPTION
**Pull request by philburk**
Fixes #2108

### CODE REVIEW

File: apps/OboeTester/app/src/main/cpp/util/WaveFileWriter.cpp [hunk 1]
```diff
@@ -60,30 +60,34 @@ void WaveFileWriter::writeFormatChunk() {
...
     // block align
     writeShortLittle((int16_t) (mSamplesPerFrame * bytesPerSample));
-    writeShortLittle((int16_t) bitsPerSample);
+    writeShortLittle((int16_t) mBitsPerSample);
+}
+
+int32_t WaveFileWriter::getDataSizeInBytes() {
+    if (mFrameCount <= 0) return INT32_MAX;
+    int64_t dataSize = ((int64_t)mFrameCount) * mSamplesPerFrame * mBitsPerSample / 8;
+    return (int32_t)std::max(dataSize, (int64_t)INT32_MAX);
```
Comment (robertwu1) [inline apps/OboeTester/app/src/main/cpp/util/WaveFileWriter.cpp:69]: shouldn't this be std::min?

Comment (philburk) [reply apps/OboeTester/app/src/main/cpp/util/WaveFileWriter.cpp]: Yes! I fixed it and used od to check the chunk size bytes. They are correct now.

**Review by robertwu1 — APPROVED** [review]
