### PR TITLE
oboe: use shared_ptr for callbacks

### LINKED ISSUE #1603: The client receives the callback onErrorAfterClose from oboe even if the audio stream is closed.  [ Same as Issue 1578]
It is the same as Issue 1578, https://github.com/google/oboe/issues/1578, which is closed, but I don't get the right answer.
To draw attention, I am not able to reopen the previous one so open a new one. Please reopen 1578 or give a comment here. Thanks.

Android version(s):
Android 8.1+
Android device(s):
Samsung Galaxy Note10+, Samsung Galaxy S21 Ultra 5G, Google Pixel 5, Samsung Galaxy A70, Samsung Galaxy A72, etc..

Oboe version:
OboeVersion1.5.0

App name used for testing:
Cisco WebexMeeting App
https://play.google.com/store/apps/details?id=com.cisco.webex.meetings&hl=en_US&gl=US

Short description
We saw a lot of crash issues reported from the Google Console and receives some client logs for that.
However, it is very hard to reproduce the issue locally
Please give advice about the root causes and how to prevent them.

The key question is why the client receives the callback onErrorAfterClose from oboe even if the audio stream is closed.
Client log:
// stop the stream (thread id 2079)
NATIVE_WME 0:0 07/18/2022 01:46:59 737 I [TID:2079][NATIVE_TID:18036][AudioEngine] [CallID=33558529]WbxAndroidAudioPlaybackNative::StopStream end, stream = 0xb400007afccefd80, stream->getState() = 10,this=0xb400007a27418018
// then close the stream (thread id 2079)
NATIVE_WME 0:0 07/18/2022 01:46:59 778 I [TID:2079][NATIVE_TID:18036][AudioEngine] [CallID=33558529]WbxAndroidAudioPlaybackNative::CloseStream end, stream = 0xb400007afccefd80, stream->getState() = 12,this=0xb400007a27418018
// deconstruct the object (thread id 2079)
NATIVE_WME 0:0 07/18/2022 01:46:59 780 I [TID:2079][NATIVE_TID:18036][AudioEngine] [CallID=33558529]WbxAndroidAudioPlaybackNative::~WbxAndroidAudioPlaybackNative,this=0xb400007a27418018
// receives the callback onErrorAfterClose from oboe (thread id 22077)
NATIVE_WME 0:0 07/18/2022 01:46:59 791 I [TID:2210][NATIVE_TID:22077][AudioEngine] [CallID=33558529]WbxAndroidAudioPlaybackNative::onErrorAfterClose, audioStream = 0xb400007afccefd80, error = ErrorDisconnected,this=0xb400007a27418018
// then the crash happens on WbxAndroidAudioPlaybackNative::onErrorAfterClose since the WbxAndroidAudioPlaybackNative object has been destroyed.

CRASH ISSUE:

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)
WbxAndroidAudioPlaybackNative::RestartStreamAfterClose(int)

pid: 0, tid: 0 >>> com.cisco.webex.meetings <<<

backtrace:
#00 pc 00000000000d6f4c /data/app/~~ikG_Vy5Itp7JxfLlKVZwdg==/com.cisco.webex.meetings-d7eqCeNia7yKgcVzOSTtuA==/lib/arm64/libaudioengine.so (WbxAndroidAudioPlaybackNative::RestartStreamAfterClose(int)+700)
#00 pc 00000000000d7abc /data/app/~~ikG_Vy5Itp7JxfLlKVZwdg==/com.cisco.webex.meetings-d7eqCeNia7yKgcVzOSTtuA==/lib/arm64/libaudioengine.so (WbxAndroidAudioPlaybackNative::onErrorAfterClose(oboe::AudioStream*, oboe::Result)+252)
#00 pc 000000000001c80c /data/app/~~ikG_Vy5Itp7JxfLlKVZwdg==/com.cisco.webex.meetings-d7eqCeNia7yKgcVzOSTtuA==/lib/arm64/liboboe.so (void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_deletestd::__ndk1::__thread_struct >, void ()(std::__ndk1::shared_ptroboe::AudioStream, oboe::Result), std::__ndk1::shared_ptroboe::AudioStream, oboe::Result> >(void)+80)
#00 pc 00000000000b0048 /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
#00 pc 00000000000503c8 /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

---------

Screen Shot 2022-08-09 at 4 28 02 PM

### PR DESCRIPTION
**Pull request by philburk**
Pass data and error callbacks to builder using a shared_ptr. Deprecate methods that pass raw pointers.

This is to avoid the callback getting deleted while the error callback is active.

Fixes #1603

### CODE REVIEW

File: apps/OboeTester/app/src/main/cpp/TestErrorCallback.cpp [hunk 1]
```diff
@@ -24,14 +24,19 @@ using namespace oboe;
 oboe::Result TestErrorCallback::open() {
     mCallbackMagic = 0;
     mDataCallback = std::make_unique<MyDataCallback>();
```
Comment (philburk) [inline apps/OboeTester/app/src/main/cpp/TestErrorCallback.cpp:26]: Should be make_shared.

File: include/oboe/AudioStreamBuilder.h [hunk 2]
```diff
@@ -354,11 +354,31 @@ class AudioStreamBuilder : public AudioStreamBase {
...
+
+    /**
+    * Pass a raw pointer to a data callback. This is not recommended because the dataCallback
+    * object might get deleted by the app while it is being used.
+    *
+    * @deprecated Call setDataCallback(std::shared_ptr<AudioStreamDataCallback>) instead.
+    * @param dataCallback
+    * @return pointer to the builder so calls can be chained
+    */
+    AudioStreamBuilder *setDataCallback(AudioStreamDataCallback *dataCallback) {
```
Comment (robertwu1) [inline include/oboe/AudioStreamBuilder.h:379]: Should we deprecate this? There may be performance hits with shared_ptr on the dataCallback.

Can we measure timing somehow with some test to verify there is no regression?

File: include/oboe/AudioStreamBuilder.h [hunk 3]
```diff
@@ -354,11 +354,31 @@ class AudioStreamBuilder : public AudioStreamBase {
...
+     * We pass a shared_ptr so that the sharedDataCallback object cannot be deleted
+     * before the stream is deleted.
+     *
      * @param dataCallback
      * @return pointer to the builder so calls can be chained
      */
-    AudioStreamBuilder *setDataCallback(oboe::AudioStreamDataCallback *dataCallback) {
+    AudioStreamBuilder *setDataCallback(std::shared_ptr<AudioStreamDataCallback> sharedDataCallback) {
+        // Use this raw pointer in the rest of the code to retain backwards compatibility.
+        mDataCallback = sharedDataCallback.get();
```
Comment (robertwu1) [inline include/oboe/AudioStreamBuilder.h:365]: Are we sure that this works as intended? There is nothing stopping the raw pointer from getting deleted somewhere else in the code.

File: include/oboe/AudioStreamBuilder.h (hunk 2 above)
Comment (philburk) [reply include/oboe/AudioStreamBuilder.h:379]: We use the stored raw pointer for all the real-time callbacks. So there should be no performance impact.

File: include/oboe/AudioStreamBuilder.h (hunk 3 above)
Comment (philburk) [reply include/oboe/AudioStreamBuilder.h:365]: We control Oboe and can promise not to delete the raw pointer. Maybe we should add a comment to that effect. We did not create the callback and should not directly delete it. That would be a bad bug.

The callback object is created by the app and shared with Oboe. Oboe AudioStream will hold a shared pointer so we know the callback will not get deleted by the app while the AudioStream still exists. And if the AudioStream is created with a shared_ptr then we know it will exist for the duration of the error callback.

It is always possible to delete some raw pointer and mess things up if we try. The goal is to make it possible for apps to  be safe if they try. Before this change, it was hard for apps to be safe even when they tried.

**Review by robertwu1 — APPROVED** [review]
