### PR TITLE
Tests: Fix unit tests so all tests pass

### LINKED ISSUE #232: Test hangs on emulator API 21
When running tests on the emulator API 21 the following test hangs: 

    StreamClosedReturnValues.GetChannelCountReturnsLastKnownValue

This is probably because the emulator is unable to open an audio stream.

### LINKED ISSUE #346: Failing test on API 19 emulator: StreamClosedReturnValues.GetDirectionReturnsLastKnownValue
When running the unit tests on an API 19 emulator I get the following test failure and crash: 

01-07 16:54:21.506 8591-8605/com.google.oboe.tests.unittestrunner D/com.google.oboe.tests.unittestrunner.MainActivity: [ RUN      ] StreamClosedReturnValues.GetDirectionReturnsLastKnownValue
01-07 16:54:21.516 8607-8607/? W/AudioRecord: AUDIO_INPUT_FLAG_FAST denied by client
01-07 16:54:21.516 1176-1369/? W/AudioPolicyManagerBase: getInput() could not find profile for device 80000004, samplingRate 48000, format 1,channelMask 000c
01-07 16:54:21.516 8607-8607/? E/AudioRecord: Could not get audio input for record source 6
01-07 16:54:21.516 8607-8607/? E/libOpenSLES: android_audioRecorder_realize(0xb7cf2670) error creating AudioRecord object
01-07 16:54:21.516 8607-8607/? W/libOpenSLES: Leaving Object::Realize (SL_RESULT_CONTENT_UNSUPPORTED)
01-07 16:54:21.516 8607-8607/? A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 8607 (testOboe)
01-07 16:54:21.516 8591-8605/com.google.oboe.tests.unittestrunner D/com.google.oboe.tests.unittestrunner.MainActivity: /Users/donturner/Code/workspace-android/oboe/tests/testStreamClosedMethods.cpp:41: Failure
01-07 16:54:21.516 8591-8605/com.google.oboe.tests.unittestrunner D/com.google.oboe.tests.unittestrunner.MainActivity: Expected equality of these values:
01-07 16:54:21.516 8591-8605/com.google.oboe.tests.unittestrunner D/com.google.oboe.tests.unittestrunner.MainActivity:   r
01-07 16:54:21.516 8591-8605/com.google.oboe.tests.unittestrunner D/com.google.oboe.tests.unittestrunner.MainActivity:     Which is: 4-byte object <80-FC FF-FF>
01-07 16:54:21.516 8591-8605/com.google.oboe.tests.unittestrunner D/com.google.oboe.tests.unittestrunner.MainActivity:   Result::OK
01-07 16:54:21.516 8591-8605/com.google.oboe.tests.unittestrunner D/com.google.oboe.tests.unittestrunner.MainActivity:     Which is: 4-byte object <00-00 00-00>
01-07 16:54:21.516 8591-8605/com.google.oboe.tests.unittestrunner D/com.google.oboe.tests.unittestrunner.MainActivity: Failed to open stream ErrorInternal

It looks like the API 19 emulator encounters a problem creating recording streams.

### LINKED ISSUE #772: RecordingFormatUnspecifiedReturnsFloatOnMarshmallowAndLater test hangs
Android Version(s): Q
Android Device(s): Pixel 2
Oboe Version: 1.3.2

**Short Description**

Unit test hangs at:
StreamOpen.RecordingFormatUnspecifiedReturnsFloatOnMarshmallowAndLater

**Steps To Reproduce**

Follow instructions at: https://github.com/google/oboe/tree/master/tests
to run the tests.
In https://github.com/google/oboe/blob/master/tests/CMakeLists.txt
comment out every test except "testStreamOpen.cpp"

**Expected behavior**

Test should complete and say "[ PASSED ] ? tests."

**Actual behavior**

Test hangs at:
StreamOpen.RecordingFormatUnspecifiedReturnsFloatOnMarshmallowAndLater
every time.

**Additional context**
Also hangs on master on P3a.

### LINKED ISSUE #933: unit tests do not run on Nexus 6P on Android 6.0.1, bad logcat option?
Android version(s): 6.0.1
Android device(s): Nexus 6P
Oboe version: 1.4.2
App name used for testing: 
unit tests
 
**Short description**
(Please only report one bug per Issue. Do not combine multiple bugs.)

**Reproduce**
Follow instructions at: https://github.com/google/oboe/tree/master/tests
to run the tests.

**Expected behavior**
Test runs to completion and and reports number of tests that PASS.

**Actual behavior**

Tests did not run:

    BUILD SUCCESSFUL in 36s
    25 actionable tasks: 1 executed, 24 up-to-date
    ~/github/oboe/tests
    Starting app - Check your device for test results
    Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] 
        cmp=com.google.oboe.tests.unittestrunner/.MainActivity }
    Unrecognized Option -

### LINKED ISSUE #1103: Unit test on API 22 emulator crashes in RecordingFormatFloatReturnsErrorBeforeMarshmallow
Android version(s): 22 L
Android device(s): Galaxy Nexus emulator
Oboe version: 1.4.3, almost 1.5
App name used for testing:  Oboe unit tests

**Short description**
Run Oboe unit tests on the emulator.

**Steps to reproduce**
See https://github.com/google/oboe/tree/master/tests

**Expected behavior**
All pass

**Actual behavior**
StreamOpen.RecordingFormatUnspecifiedReturnsI16BeforeMarshmallow. fails
I/DEBUG   ( 1181): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0

**Device**
Galaxy Nexus emulator

### LINKED ISSUE #1501: Upgrade UnitTestRunner to Android 31
UnitTestRunner needs to be updated to Android 31.

File permissions have changed drastically after Android 28. UnitTestRunner currently moves the testOboe from the assets/arm64-v8a/testOboe to /data/user/0/com.google.oboe.tests.unittestrunner/files.

With new locked down permissions in Android, we now need write to /data/app/com.google.oboe.tests.unittestrunner-2Fz_VhZta8rHAQgepO520w==/lib/arm64. Also, we need to request storage permissions. See [this](https://www.raywenderlich.com/9577211-scoped-storage-in-android-10-getting-started) for more details.

### PR DESCRIPTION
**Pull request by robertwu1**
Fixes #1501
Fixes #933
Fixes #1103
Fixes #772
Fixes #346
Fixes #232

In the last couple of Android releases, file permissions have become very tight. Before, we were moving the binary to a specific location, giving execute privileges to it, and running it directly in Java. This method is clearly risky and is blocked.

In order to upgrade the UnitTestRunner app, the following was done.

1. In run_tests.sh, the test binary is put under ${TEST_RUNNER_DIR}/app/src/main/jniLibs.
2. For Android O and over, building AndroidTestRunner moves this binary from ${TEST_RUNNER_DIR}/app/src/main/jniLibs and moves it to /data/app/~~WaKVjcw3K51emFW_rzq8ng==/com.google.oboe.tests.unittestrunner-0A3aNOPlAJ-9TpG86JRNfQ==/lib/arm64/libtestOboe.so
3.  For Android O and over, UnitTestRunner now can execute the binary from the new spot (getApplicationInfo().nativeLibraryDir).

The old method is still used for Android N and below.

A couple of other quality of life changes were added in this PR:
1. Cleaned up warnings in MainActivity.java. This adds some StringBuilder and some lambdas.
2. Only print logs in ${TEST_RUNNER_PACKAGE_NAME}.MainActivity and OboeAudio instead of all logcats at the end of ./run_tests.sh.
3. Removed empty assets folder in favor of creating jniLibs and assets dynamically. This is the .gitignore change.
4. Clean up build files on every build. When testing on different devices, old build devices makes the compile fail.
5. Loosen requirements on tests so emulators can pass.

All the Android emulators and real phones I tested with pass with the changes.

One of the test failures is actually a code failure in OpenSL ES. I have opened #1582 to fix this.

### CODE REVIEW

File: tests/testStreamFramesProcessed.cpp [hunk 1]
```diff
@@ -55,7 +55,7 @@ TEST_P(StreamFramesProcessed, VerifyFramesProcessed) {
 
     AudioStreamDataCallback *callback = new FramesProcessedCallback();
     mBuilder.setDirection(direction)
-            ->setFormat(AudioFormat::Float)
+            ->setFormat(AudioFormat::I16)
```
Comment (philburk) [inline tests/testStreamFramesProcessed.cpp:58]: Why was this changed to I16?

**Review by philburk — COMMENTED** [review]
Great work!

File: tests/testStreamFramesProcessed.cpp (hunk 1 above)
Comment (robertwu1) [reply tests/testStreamFramesProcessed.cpp:58]: OpenSL ES doesn't support Float below API 23

File: tests/testReturnStop.cpp [hunk 2]
```diff
@@ -29,21 +29,20 @@ static constexpr int kTimeoutInNanos = 500 * kNanosPerMillisecond;
...
+
+    int getMaxCallbacks() const { return kMaxCallbacks; }
+
+    std::atomic<int> callbackCount{0};
+    
 private:
-	// I get strange linker errors with GTest if I try to reference this directly.
-	static constexpr int kMaxCallbacks = 4;
+    // I get strange linker errors with GTest if I try to reference this directly.
+    static constexpr int kMaxCallbacks = 400;
```
Comment (robertwu1) [inline tests/testReturnStop.cpp:45]: Increased to 400 because callbacks can complete before start

File: tests/testReturnStop.cpp [hunk 3]
```diff
@@ -69,56 +68,61 @@ TEST_P(StreamReturnStop, VerifyStreamReturnStop) {
...
+    const bool useRequestStart = std::get<3>(GetParam());
 
     ReturnStopCallback *callback = new ReturnStopCallback();
     mBuilder.setDirection(direction)
-		    ->setAudioApi(audioApi)
-            ->setFormat(AudioFormat::Float)
+            ->setFormat(AudioFormat::I16)
             ->setPerformanceMode(performanceMode)
             ->setDataCallback(callback);
+    if (mBuilder.isAAudioRecommended()) {
```
Comment (robertwu1) [inline tests/testReturnStop.cpp:78]: API level 26 is broken for AAudio

File: tests/testReturnStop.cpp [hunk 4]
```diff
@@ -69,56 +68,61 @@ TEST_P(StreamReturnStop, VerifyStreamReturnStop) {
...
+        // Oboe has two ways to start a stream.
+        if (useRequestStart) {
+            r = mStream->requestStart();
+        } else {
+            r = mStream->start();
+        }
+        ASSERT_EQ(r, Result::OK) << "Failed to start stream. " << convertToText(r);
+    
+        // Wait for callbacks to complete.
+        const int kMaxCallbackPeriodMillis = 500;
```
Comment (robertwu1) [inline tests/testReturnStop.cpp:97]: Increased number for more leniency

File: tests/testStreamClosedMethods.cpp [hunk 5]
```diff
@@ -211,11 +211,12 @@ TEST_F(StreamClosedReturnValues, GetFramesWrittenReturnsLastKnownValue){
     mBuilder.setFormat(AudioFormat::I16);
     mBuilder.setChannelCount(1);
     ASSERT_TRUE(openStream());
+    ASSERT_EQ(mStream->setBufferSizeInFrames(mStream->getBufferCapacityInFrames()), Result::OK);
```
Comment (robertwu1) [inline tests/testStreamClosedMethods.cpp:214]: Without setting setBufferSizeInFrames, OpenSL ES has a bufferSize of 0 so write doesn't work

File: tests/testStreamClosedMethods.cpp [hunk 6]
```diff
@@ -236,14 +236,12 @@ TEST_F(StreamClosedReturnValues, GetFramesReadReturnsLastKnownValue) {
     ASSERT_TRUE(openStream());
     mStream->start();
 
-/*
     int16_t buffer[192];
-    auto r = mStream->read(&buffer, 192, 0);
+    auto r = mStream->read(&buffer, 192, 1000 * kNanosPerMillisecond);
```
Comment (robertwu1) [inline tests/testStreamClosedMethods.cpp:240]: Adding a timeout allows this to pass.

File: tests/testStreamClosedMethods.cpp [hunk 7]
```diff
@@ -301,7 +299,7 @@ TEST_F(StreamClosedReturnValues, WaitForStateChangeReturnsClosed){
     ASSERT_TRUE(openAndCloseStream());
     StreamState next;
     Result r = mStream->waitForStateChange(StreamState::Open, &next, 0);
-    ASSERT_EQ(r, Result::ErrorClosed) << convertToText(r);
+    EXPECT_TRUE(r == Result::OK || r == Result::ErrorClosed) << convertToText(r);
```
Comment (robertwu1) [inline tests/testStreamClosedMethods.cpp:302]: The idiom here is r == Result::OK || r == Result::ErrorClosed. This is used throughout our tests

File: tests/testStreamFramesProcessed.cpp [hunk 8]
```diff
@@ -70,10 +70,11 @@ TEST_P(StreamFramesProcessed, VerifyFramesProcessed) {
     sleep(PROCESS_TIME_SECONDS);
 
     // The frames written should be close to sampleRate * PROCESS_TIME_SECONDS
+    const int kDeltaFramesWindowInFrames = 30000;
```
Comment (robertwu1) [inline tests/testStreamFramesProcessed.cpp:73]: Changed this to a const instead of a multiple of the sample rate. Drifting doesn't generally get worse with a higher sample rate

File: tests/testStreamOpen.cpp [hunk 9]
```diff
@@ -233,15 +238,17 @@ TEST_F(StreamOpen, AAudioFramesPerCallbackNone) {
...
-        timeout--;
+    if (mStream->getAudioApi() == AudioApi::AAudio) {
+        ASSERT_EQ(mStream->setBufferSizeInFrames(mStream->getBufferCapacityInFrames()), Result::OK);
+        ASSERT_EQ(mStream->requestStart(), Result::OK);
+        int timeout = 20;
+        while (callback.framesPerCallback == 0 && timeout > 0) {
+            usleep(50 * 1000);
+            timeout--;
+        }
+        ASSERT_EQ(kRequestedFramesPerCallback, callback.framesPerCallback);
```
Comment (robertwu1) [inline tests/testStreamOpen.cpp:249]: framesPerCallback not supported in OpenSL ES

File: tests/testStreamClosedMethods.cpp (hunk 5 above)
Comment (robertwu1) [reply tests/testStreamClosedMethods.cpp:214]: Created separate PR #1582 to fix this code bug. This PR will be too noisy otherwise.

File: tests/testStreamOpen.cpp (hunk 9 above)
Comment (robertwu1) [reply tests/testStreamOpen.cpp]: not framespercallback but setBufferSizeInFrames for OpenSL ES streams without callbacks. Removed this instead.

File: tests/testStreamFramesProcessed.cpp (hunk 1 above)
Comment (robertwu1) [reply tests/testStreamFramesProcessed.cpp:58]: For input streams, OpenSL ES doesn't support Float below API 23. For output streams, OpenSL ES doesn't support Float below API 21.

**Review by philburk — APPROVED** [review]
