### PR TITLE
OpenSL ES: Call processBufferCallback before setting the playstate to playing

### LINKED ISSUE #1567: onAudioReady() is called simultaneously from two threads on OpenSL ES backend
Android version(s): 10 and 11
Android device(s): Multiple, see below
Oboe version: 1.6.1
App name used for testing:  -
 
**Short description**
When calling requestStart() for an OpenSL ES output stream, onAudioReady() is called from the thread that called requestStart(), and simultaneously from an AudioTrack thread.

**Steps to reproduce**
The issue may be hard to reproduce. It occurs in our game within 5 minutes of starting the game.

Call requestStart() for an OpenSL ES output stream, and observe that onAudioReady() is called from two threads simultaneously.

**Expected behavior**
onAudioReady() is not called from multiple threads simultaneously.

**Actual behavior**
onAudioReady() is called from two threads simultaneously.

**Device**
- Nokia 9 PureView (Android 10)
- Samsung Galaxy A12 (Android 11)

**Any additional context**
Stack trace of the thread that called requestStart():
```
> libNativeGame.so!OboeChannelCallback::onAudioReady(oboe::AudioStream*, void*, int)(OboeChannelCallback * this, oboe::AudioStream * stream, void * buffer, int32_t frame_count) Line 37	c++14
  liboboe.so!non-virtual thunk to oboe::AudioSourceCaller::onProcessFixedBlock(unsigned char*, int)()	unknown
  liboboe.so!FixedBlockReader::read(unsigned char*, int)()	unknown
  liboboe.so!oboe::SourceFloatCaller::onProcess(int)()	unknown
  liboboe.so!oboe::flowgraph::FlowGraphPortFloatOutput::pullData(long, int)()	unknown
  liboboe.so!oboe::flowgraph::SampleRateConverter::onProcess(int)()	unknown
  liboboe.so!oboe::flowgraph::FlowGraphPortFloatOutput::pullData(long, int)()	unknown
  liboboe.so!oboe::flowgraph::FlowGraphSink::pullData(int)()	unknown
  liboboe.so!oboe::flowgraph::SinkFloat::read(void*, int)()	unknown
  liboboe.so!non-virtual thunk to oboe::FilterAudioStream::onAudioReady(oboe::AudioStream*, void*, int)()	unknown
  liboboe.so!oboe::AudioStream::fireDataCallback(void*, int)()	unknown
  liboboe.so!oboe::AudioStreamOpenSLES::processBufferCallback(SLAndroidSimpleBufferQueueItf_ const* const*)()	unknown
  liboboe.so!oboe::AudioOutputStreamOpenSLES::requestStart()()	unknown
```

Stack trace of AudioTrack thread:
```
> libNativeGame.so!OboeChannelCallback::onAudioReady(oboe::AudioStream*, void*, int)(OboeChannelCallback * this, oboe::AudioStream * stream, void * buffer, int32_t frame_count) Line 37	c++14
  liboboe.so!non-virtual thunk to oboe::AudioSourceCaller::onProcessFixedBlock(unsigned char*, int)()	unknown
  liboboe.so!FixedBlockReader::read(unsigned char*, int)()	unknown
  liboboe.so!oboe::SourceFloatCaller::onProcess(int)()	unknown
  liboboe.so!oboe::flowgraph::FlowGraphPortFloatOutput::pullData(long, int)()	unknown
  liboboe.so!oboe::flowgraph::SampleRateConverter::onProcess(int)()	unknown
  liboboe.so!oboe::flowgraph::FlowGraphPortFloatOutput::pullData(long, int)()	unknown
  liboboe.so!oboe::flowgraph::FlowGraphSink::pullData(int)()	unknown
  liboboe.so!oboe::flowgraph::SinkFloat::read(void*, int)()	unknown
  liboboe.so!non-virtual thunk to oboe::FilterAudioStream::onAudioReady(oboe::AudioStream*, void*, int)()	unknown
  liboboe.so!oboe::AudioStream::fireDataCallback(void*, int)()	unknown
  liboboe.so!oboe::AudioStreamOpenSLES::processBufferCallback(SLAndroidSimpleBufferQueueItf_ const* const*)()	unknown
  libwilhelm.so!audioTrack_callBack_pullFromBuffQueue(int, void*, void*)()	unknown
  libaudioclient.so!android::AudioTrack::processAudioBuffer()()	unknown
  libaudioclient.so!android::AudioTrack::AudioTrackThread::threadLoop()()	unknown
  libutils.so!android::Thread::_threadLoop(void*)()	unknown
  libandroid_runtime.so!android::AndroidRuntime::javaThreadShell(void*)()	unknown
  libutils.so!thread_data_t::trampoline(thread_data_t const*)()	unknown
  libc.so!__pthread_start(void*)()	unknown
  libc.so!__start_thread()	unknown
```

### PR DESCRIPTION
**Pull request by robertwu1**
Fixes #1567

If processBufferCallback() is called after setPlayState_l(SL_PLAYSTATE_PLAYING), there could be cases where onAudioReady() is called from two threads.

We should not release the lock just for processBufferCallback(), so there is a minor refactor here. processBufferCallback() now returns a bool and that bool is used to determine whether requestStop_l() should be called.

### CODE REVIEW

File: src/opensles/AudioOutputStreamOpenSLES.cpp [hunk 1]
```diff
@@ -298,15 +298,23 @@ Result AudioOutputStreamOpenSLES::requestStart() {
...
+        bool shouldStopStream = processBufferCallback(mSimpleBufferQueueInterface);
+        if (shouldStopStream) {
+            LOGD("Stopping the current stream.");
+            if (requestStop_l() != Result::OK) {
+                LOGW("Failed to flush the stream. Error %s", convertToText(flush()));
+            }
+        }
+    }
+
     Result result = setPlayState_l(SL_PLAYSTATE_PLAYING);
```
Comment (philburk) [inline src/opensles/AudioOutputStreamOpenSLES.cpp:314]: Can skip setting PLAYSTATE if shouldStopStream is true.

**Review by philburk — CHANGES_REQUESTED** [review]

**Comment by flamme** [comment]
Do you also need to call requestStop_l in bqCallbackGlue? See https://github.com/google/oboe/blob/1e19ec7850c499c8af17eacf6672f0aa534a8252/src/opensles/AudioStreamOpenSLES.cpp#L349

File: src/opensles/AudioOutputStreamOpenSLES.cpp (hunk 1 above)
Comment (robertwu1) [reply src/opensles/AudioOutputStreamOpenSLES.cpp:302]: Not needed as we are caching getBufferDepth

**Comment by robertwu1** [comment]
> Do you also need to call requestStop_l in bqCallbackGlue? See
> 
> https://github.com/google/oboe/blob/1e19ec7850c499c8af17eacf6672f0aa534a8252/src/opensles/AudioStreamOpenSLES.cpp#L349

Nice catch!

**Comment by robertwu1** [comment]
Most recent commit simply caches the buffer depth as we suspect that calling setPlayState_l changes the buffer depth

**Review by philburk — APPROVED** [review]
