### PR TITLE
OboeTester: use 2 burst min for glitch test

### LINKED ISSUE #1560: OboeTester Glitch test should use BufferSize of 2 bursts
On Raven, the AutoGlitch test fails on test 10, which is not low latency.
The burst size is 1924 and the buffer size is 1924.
We should use a minimum of two bursts for BufferSize

### PR DESCRIPTION
**Pull request by philburk**
Was using 1/2 capacity, which is sometimes only one burst.

Fixes #1560

### CODE REVIEW

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java [hunk 1]
```diff
@@ -257,6 +257,7 @@ protected TestResult testConfigurations() throws InterruptedException {
             // Set output size to a level that will avoid glitches.
             AudioStreamBase outStream = mAudioOutTester.getCurrentAudioStream();
             int sizeFrames = outStream.getBufferCapacityInFrames() / 2;
+            sizeFrames = Math.max(sizeFrames, 2 * outStream.getFramesPerBurst());
```
Comment (robertwu1) [inline apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java:260]: If 2 * outStream.getFramesPerBurst() is greater than outStream.getBufferCapacityInFrames(), we may overflow.

Can we add an additional Math.min(sizeFrames, outStream.getBufferCapacityInFrames())?

**Review by robertwu1 — CHANGES_REQUESTED** [review]

File: apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java (hunk 1 above)
Comment (philburk) [reply apps/OboeTester/app/src/main/java/com/mobileer/oboetester/BaseAutoGlitchActivity.java:260]: setBufferSizeInFrames() is clipped in Oboe and AAudio against the capacity. So this is safe.
It returns the actual size after clipping and quantizing to multiples of the burst size.

Also we try to ensure the capacity is at least two bursts.

**Review by robertwu1 — APPROVED** [review]
