### PR TITLE
Liveeffect: fix crash on exit

### LINKED ISSUE #852: LiveEffect should process samples from input to output.
Instead of using memcpy(), the sample code should move each sample from input to output.
That will make it easier for developers to make changes.
We could, for example, apply a gain change of 0.9 to each sample.

https://github.com/google/oboe/blob/master/samples/LiveEffect/src/main/cpp/FullDuplexPass.h

### LINKED ISSUE #1113: LiveEffect crashes on exit
Android version(s): RQ1A
Android device(s): Pixel 3a
Oboe version: 1.5.0 candidate
App name used for testing: LiveEffect
 
**Short description**
LiveEffect has a native crash with a NULL pointer of bad address when exiting.

**Steps to reproduce**
In a terminal:    adb logcat *:F
Launch LiveEffect
Select OpenSL ES (optional)
Tap START
Tap STOP
Tap BACK button

**Expected behavior**

No crash.

**Actual behavior**

Crash observed in logcat.

11-25 13:59:22.288 11461 11461 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc1f9830000000071

11-25 13:59:22.569 11461 11461 F DEBUG   :       #00 pc 000000000005adc4  /data/app/~~FRTqKF6YenZJ5qAzAEGRgA==/com.google.oboe.samples.liveeffect-xvcrj64_iTK-Y60sIUJSdQ==/lib/arm64/libliveEffect.so (FullDuplexStream::stop()+76) (BuildId: 0958e065dd7daeb4923f76935971a9ba50480c0a)
11-25 13:59:22.569 11461 11461 F DEBUG   :       #01 pc 0000000000058de0  /data/app/~~FRTqKF6YenZJ5qAzAEGRgA==/com.google.oboe.samples.liveeffect-xvcrj64_iTK-Y60sIUJSdQ==/lib/arm64/libliveEffect.so (LiveEffectEngine::~LiveEffectEngine()+64) (BuildId: 0958e065dd7daeb4923f76935971a9ba50480c0a)
11-25 13:59:22.569 11461 11461 F DEBUG   :       #02 pc 0000000000058ffc  /data/app/~~FRTqKF6YenZJ5qAzAEGRgA==/com.google.oboe.samples.liveeffect-xvcrj64_iTK-Y60sIUJSdQ==/lib/arm64/libliveEffect.so (LiveEffectEngine::~LiveEffectEngine()+36) (BuildId: 0958e065dd7daeb4923f76935971a9ba50480c0a)
11-25 13:59:22.569 11461 11461 F DEBUG   :       #03 pc 000000000005b1e0  /data/app/~~FRTqKF6YenZJ5qAzAEGRgA==/com.google.oboe.samples.liveeffect-xvcrj64_iTK-Y60sIUJSdQ==/lib/arm64/libliveEffect.so (Java_com_google_oboe_samples_liveEffect_LiveEffectEngine_delete+68) (BuildId: 0958e065dd7daeb4923f76935971a9ba50480c0a)

### PR DESCRIPTION
**Pull request by philburk**
Use std::shared_ptr in FullDuplexStream.
Explicitly process the samples in the callback instead
of just using memcpy. This will be easier to modify.

Fixes #1113
Fixes #852

### CODE REVIEW

File: samples/LiveEffect/src/main/cpp/LiveEffectEngine.cpp [hunk 1]
```diff
@@ -114,11 +115,11 @@ oboe::Result  LiveEffectEngine::openStreams() {
  * @param builder The recording stream builder
```
Comment (dturner) [inline samples/LiveEffect/src/main/cpp/LiveEffectEngine.cpp:115]:
```suggestion
 * @param builder The recording stream builder
 * @param sampleRate The desired sample rate of the recording stream
```
