### PR TITLE
opensles: clean up after failed open

### LINKED ISSUE #1541: Oboe may need handle the case that openStream failed too many times
Android version(s): 
Android device(s):
Oboe version: latest
App name used for testing: 
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 
**Short description**

**Steps to reproduce**
1. disallow cellphone's microphone permission for oboe app
2. try openStream many times
3. then give permission for oboe app
4. openStream maybe failed

By investigate the oboe source code, I think here may have issue, could you help double check?

image

### PR DESCRIPTION
**Pull request by philburk**
There were resource leaks if the open failed.
So now it calls close() internally if open fails.

Fixes #1541

### CODE REVIEW

File: src/opensles/AudioInputStreamOpenSLES.cpp [hunk 1]
```diff
@@ -225,7 +226,7 @@ Result AudioInputStreamOpenSLES::close() {
     if (getState() == StreamState::Closed){
         result = Result::ErrorClosed;
     } else {
-        requestStop_l();
+        (void) requestStop_l();
```
Comment (robertwu1) [inline src/opensles/AudioInputStreamOpenSLES.cpp:229]: I haven't seem this idiom of casting to void before. I'm just curious about the reasoning behind this.

**Review by robertwu1 — APPROVED** [review]

File: src/opensles/AudioInputStreamOpenSLES.cpp (hunk 1 above)
Comment (philburk) [reply src/opensles/AudioInputStreamOpenSLES.cpp:229]: It says "I know this function returns a result code. But I don't care because I will just keep going even if it returns an error code. So I am not even going to look at it.".
