### PR TITLE
oboe: add Quirk for broken mono on S9

### LINKED ISSUE #824: Audio input pitched down 1 octave on Samsung S9, broken mono
Android Version(s): 10
Android Device(s): Samsung S9 (SM-G960F)
Oboe Version: 1.3.3 and 1.2.4

**Short Description**
Using Oboe in full-duplex, the sound from the microphone sounds pitched down by one octave. This is on a stock version of android 10 (i.e. samsung's official version), on a newly wiped phone. 

**Steps To Reproduce**
Compile and run the FXLab demo app, and press the speaker button in the top right to unmute (happens both with headphones plugged in and without)

**Expected behavior**
Should pass through the signal normally.

**Actual behavior**
The sound sounds as if it is pitched down one octave, additionally, there are discontinuities in the waveform recorded at 3072 frame intervals (buffer size is 96 frames, so that's 32 buffers). Also, very suspiciously, the input buffer is a series of doubled up numbers, as if it's a stereo signal consisting of a mono signal interleaved with itself.

e.g.

-0.062038030475378
-0.062038030475378
-0.055203106254339
-0.055203106254339
-0.052048526704311
-0.052048526704311

I'm guessing the discontinuity is happening because the input buffer hasn't finished being pulled through the app yet (because it's playing at half speed) before it gets overwritten by incoming audio from the system

**Additional context**

(Sound file attached)

I'm happy to keep testing this and other stuff on the S9 if I can be of any help

### PR DESCRIPTION
**Pull request by philburk**
The Samsung S9 does not support mono properly.
It is actually stereo. So on that device, we open a stereo
stream and then convert it to mono by extracting
the first channel.

Fixes #824

### CODE REVIEW

File: src/common/QuirksManager.cpp [hunk 1]
```diff
@@ -51,11 +52,24 @@ int32_t QuirksManager::DeviceQuirks::clipBufferSize(AudioStream &stream,
...
 }
 
+bool QuirksManager::DeviceQuirks::isAAudioMMapPossible(const AudioStreamBuilder &builder) {
+    bool isSampleRateCompatible =
+            builder.getSampleRate() == oboe::Unspecified
+            || builder.getSampleRate() == kCommonNativeRate
+            || builder.getSampleRateConversionQuality() != SampleRateConversionQuality::None;
+    return builder.getPerformanceMode() == PerformanceMode::LowLatency
+            && isSampleRateCompatible
+            && builder.getChannelCount() <= 2;
```
Comment (philburk) [inline src/common/QuirksManager.cpp:62]: From b/155341396
> When we select Camcorder , it works well because mmap open fails and it works as legacy path.

File: CMakeLists.txt [hunk 2]
```diff
@@ -30,6 +30,7 @@ set (oboe_sources
     src/flowgraph/ClipToRange.cpp
     src/flowgraph/ManyToMultiConverter.cpp
     src/flowgraph/MonoToMultiConverter.cpp
+    src/flowgraph/MultiToMonoConverter.cpp
```
Comment (dturner) [inline CMakeLists.txt:33]: Couldn't both `MultiToMono` and `MonoToMulti` be contained within single `ChannelCountConverter` which takes an arbitrary number of input and output channels?

File: src/common/DataConversionFlowGraph.cpp [hunk 3]
```diff
@@ -139,27 +140,43 @@ Result DataConversionFlowGraph::configure(AudioStream *sourceStream, AudioStream
         lastOutput = &mSource->output;
     }
 
+    if (sourceChannelCount != sinkChannelCount
+        && sourceChannelCount != 1
+        && sinkChannelCount != 1
+        ) {
+        LOGW("%s() Channel conversion %d to %d not supported.", __func__,
```
Comment (dturner) [inline src/common/DataConversionFlowGraph.cpp:147]: `LOGE` since this is an error?

File: src/common/QuirksManager.cpp [hunk 4]
```diff
@@ -115,24 +141,39 @@ bool QuirksManager::isConversionNeeded(
...
-            // b/66967812 AudioRecord does not allow FAST track for stereo capture in O
-            childBuilder.setChannelCount(1);
-            conversionNeeded = true;
-        }
-        // Note that MMAP does not support mono in 8.1. But that would only matter on Pixel 1
-        // phones and they have almost all been updated to 9.0.
+    // Channel Count conversions
+    if (OboeGlobals::areWorkaroundsEnabled()
+            && builder.isChannelConversionAllowed()
+            && builder.getChannelCount() == 2 // stereo?
```
Comment (dturner) [inline src/common/QuirksManager.cpp:150]: Could these be changed to constants? I think we have `kChannelCount*` consts

File: src/common/QuirksManager.cpp [hunk 5]
```diff
@@ -115,24 +141,39 @@ bool QuirksManager::isConversionNeeded(
...
+            && isInput
+            && isLowLatency
+            && (!builder.willUseAAudio() && (getSdkVersion() == __ANDROID_API_O__))
+            ) {
+        // Workaround for heap size regression in O.
+        // b/66967812 AudioRecord does not allow FAST track for stereo capture in O
+        childBuilder.setChannelCount(1);
```
Comment (dturner) [inline src/common/QuirksManager.cpp:157]: Constant?

File: src/common/QuirksManager.cpp [hunk 6]
```diff
@@ -115,24 +141,39 @@ bool QuirksManager::isConversionNeeded(
...
+        conversionNeeded = true;
+        LOGI("QuirksManager::%s() using mono internally for low latency on O", __func__);
+    } else if (OboeGlobals::areWorkaroundsEnabled()
+               && builder.getChannelCount() == 1 // mono?
```
Comment (dturner) [inline src/common/QuirksManager.cpp:161]: Constant?

File: src/common/QuirksManager.cpp [hunk 7]
```diff
@@ -115,24 +141,39 @@ bool QuirksManager::isConversionNeeded(
...
+               && isInput
+               && mDeviceQuirks->isMonoMMapActuallyStereo()
+               && builder.willUseAAudio()
+               // Note: we might use this workaround on a device that supports
+               // MMAP but will use Legacy for this stream.  But this will only happen
+               // on devices that have the broken mono.
+               && mDeviceQuirks->isAAudioMMapPossible(builder)
+               ) {
+        // Workaround for mono actually running in stereo mode.
+        childBuilder.setChannelCount(2); // Use stereo and extract first channel.
```
Comment (dturner) [inline src/common/QuirksManager.cpp:171]: Constant

File: src/common/DataConversionFlowGraph.cpp (hunk 3 above)
Comment (philburk) [reply src/common/DataConversionFlowGraph.cpp:147]: removed

File: CMakeLists.txt (hunk 2 above)
Comment (philburk) [reply CMakeLists.txt:33]: I added a ChannelCountConverter for the previous unsupported case, eg "2:3". But it looks a bit more complex and is slower than the Mono nodes. So I kept them.

File: src/common/QuirksManager.h [hunk 8]
```diff
@@ -110,6 +110,9 @@ class QuirksManager {
 
 private:
 
+    static constexpr int32_t kChannelCountMono = 1;
```
Comment (dturner) [inline src/common/QuirksManager.h:113]: Rather than add these I think you can use the `oboe::ChannelCount::*` constants
