### PR TITLE
AAudio: add locks around reading and writing

### LINKED ISSUE #1484: Crashes in oboe::AudioStreamAAudio::read(void*, int, long) [AudioStreamAAudio.cpp:490]
Android version(s): Android 11, and 12
Android device(s): Pixel 6, Pixel 6 Pro, Redmi Note 10, and TECNO POVA 2
Oboe version: 1.6.1
App name used for testing: 
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 
Recently, we got a noticeable number of crashes in oboe::AudioStreamAAudio::read(void*, int, long) [AudioStreamAAudio.cpp:490]
The crashes have been rare before but remarkably increased recently in the latest phones and thus 99% in Android 11 and 12.

The firebase shows that
- about 50% of the crashes happened in Pixel6 and Pixel6Pro (Android 12)
- and 23% happened in Xiaomi Redmi Note 10 (Android 11)
- and 12% happened in TECNO POVA 2 (Android 11)

Another interesting pattern was that only TECNO POVA 2 crashed with SIGSEGV while all other phones crashed with SIGABRT as shown below:

Pixel6, Pixel6Pro, and Xiaomi Redmi Note 10 
```
Crashed: Thread :  SIGABRT  0x0000000000000000
#00 pc 0x89b0c libc.so 
#01 pc 0x89adc libc.so 
#02 pc 0x3774c libaaudio_internal.so 
#03 pc 0x33438 libaaudio_internal.so 
#04 pc 0x32788 libaaudio_internal.so 
#05 pc 0x351490 libbandlab_audio_engine.so (oboe::AudioStreamAAudio::read(void*, int, long) [AudioStreamAAudio.cpp:490])
#06 pc 0x2b62cc libbandlab_audio_engine.so (AudioInputDevice_Oboe::process(int) [AudioDevice_Oboe.cpp:348])
```

TECNO POVA 2
```
Crashed: Thread :  SIGSEGV  0x00000072f077c580
#00 pc 0x4a408 libc.so 
#01 pc 0x8afc libsoundtouch.so 
#02 pc 0xbe74 libsoundtouch.so 
#03 pc 0x5aaf8 libaudioclient.so 
#04 pc 0x280d8 libaaudio_internal.so 
#05 pc 0x351490 libbandlab_audio_engine.so (oboe::AudioStreamAAudio::read(void*, int, long) [AudioStreamAAudio.cpp:490])
#06 pc 0x2b62cc libbandlab_audio_engine.so (AudioInputDevice_Oboe::process(int) [AudioDevice_Oboe.cpp:348])
```

### PR DESCRIPTION
**Pull request by robertwu1**
This PR fixes an issue where AAudio segfaults if the stream is closed while read or write occurs. The main work done here is a 2 line change adding shared locks for read and write. This is relatively safe as these locks are only used as exclusive for close(), which should wait for all operations to finish in the first place.

I've updated a few things related to unit tests.
1. The unit tests to use a newer version of gradle.
2. I added tests to account to test the new AAudio shared read/write locks.
3. Unit tests wouldn't run for devices built with hardware sanitizer, so I've added a check.

Fixes #1484

### CODE REVIEW

File: tests/testStreamStop.cpp [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+        StreamState next = StreamState::Unknown;
+        auto r = mStream->requestStart();
+        EXPECT_EQ(r, Result::OK);
+        r = mStream->waitForStateChange(StreamState::Starting, &next, kTimeoutInNanos);
+        EXPECT_EQ(r, Result::OK);
+        EXPECT_EQ(next, StreamState::Started) << "next = " << convertToText(next);
+
+        AudioStream *str = mStream;
+
+        int16_t buffer[kFramesToWrite * 4] = {};
```
Comment (philburk) [inline tests/testStreamStop.cpp:67]: Declare the streams with ChannelCount(1) then you don't need the *4.

File: tests/testStreamStop.cpp [hunk 2]
```diff
@@ -0,0 +1,124 @@
...
+
+        std::thread stopper([str] {
+            usleep(3 * 1000); // 3 ms
```
Comment (philburk) [inline tests/testStreamStop.cpp:70]: This is a bit racey. Calculate the time it will take to perform the read or write and then try to land in the middle of that time.

File: tests/testStreamStop.cpp [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+            str->close();
+        });
+
+        if (shouldWrite) {
```
Comment (philburk) [inline tests/testStreamStop.cpp:74]: Can base on mStream->getDirection()

File: tests/testStreamStop.cpp [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+            r = mStream->write(&buffer, kFramesToWrite, kTimeoutInNanos);
+        } else {
+            r = mStream->read(&buffer, kFramesToWrite, kTimeoutInNanos);
+        }
+        if (r != Result::OK) {
+            FAIL() << "Could not write to audio stream: " << static_cast<int>(r);
```
Comment (philburk) [inline tests/testStreamStop.cpp:80]: read/write

File: tests/testStreamStop.cpp [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+                TestStreamStopParams({Direction::Output, AudioApi::OpenSLES, PerformanceMode::None}),
+                TestStreamStopParams({Direction::Output, AudioApi::OpenSLES, PerformanceMode::PowerSaving}),
+                TestStreamStopParams({Direction::Input, AudioApi::AAudio, PerformanceMode::LowLatency}),
+                TestStreamStopParams({Direction::Input, AudioApi::AAudio, PerformanceMode::None}),
+                TestStreamStopParams({Direction::Input, AudioApi::AAudio, PerformanceMode::PowerSaving}),
+                TestStreamStopParams({Direction::Input, AudioApi::OpenSLES, PerformanceMode::LowLatency}),
+                TestStreamStopParams({Direction::Input, AudioApi::OpenSLES, PerformanceMode::None}),
+                TestStreamStopParams({Direction::Input, AudioApi::OpenSLES, PerformanceMode::PowerSaving})
+        )
+);
```
Comment (philburk) [inline tests/testStreamStop.cpp:124]: Add newline.

**Review by philburk — CHANGES_REQUESTED** [review]
Nice!

File: tests/testStreamStop.cpp (hunk 1 above)
Comment (robertwu1) [reply tests/testStreamStop.cpp]: Good idea! Done!

File: tests/testStreamStop.cpp (hunk 4 above)
Comment (robertwu1) [reply tests/testStreamStop.cpp]: Done!

File: tests/testStreamStop.cpp (hunk 5 above)
Comment (robertwu1) [reply tests/testStreamStop.cpp]: Done! This is actually really interesting https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

File: tests/testStreamStop.cpp (hunk 3 above)
Comment (robertwu1) [reply tests/testStreamStop.cpp]: Done!

**Comment by robertwu1** [comment]
Thanks for the comments! I addressed all of them.

File: tests/testStreamStop.cpp [hunk 6]
```diff
@@ -91,6 +94,7 @@ class TestStreamStop : public ::testing::Test,
     AudioStreamBuilder mBuilder;
     AudioStream *mStream = nullptr;
     static constexpr int kTimeoutInNanos = 1000 * kNanosPerMillisecond;
+    static constexpr int64_t kSecondsPerMicroSecond = 1000000;
```
Comment (philburk) [inline tests/testStreamStop.cpp:97]: Should be called kMicroSecondsPerSecond.

**Review by philburk — CHANGES_REQUESTED** [review]

File: tests/testStreamStop.cpp (hunk 6 above)
Comment (robertwu1) [reply tests/testStreamStop.cpp]: Done!

**Review by philburk — APPROVED** [review]
