### PR TITLE
OboeTester: Fix race conditions in AudioWorkloadTest.h

### LINKED ISSUE #2258: Race condition in AudioWorkloadTrace.h
Internal bug b/424242729

### PR DESCRIPTION
**Pull request by robertwu1**
Fixes #2258

### CODE REVIEW

File: apps/OboeTester/app/src/main/cpp/cpu/AudioWorkloadTest.h [hunk 1]
```diff
@@ -291,6 +295,9 @@ class AudioWorkloadTest : oboe::AudioStreamDataCallback {
      */
     oboe::DataCallbackResult onAudioReady(oboe::AudioStream* audioStream, void* audioData,
                                           int32_t numFrames) override {
+        if (audioStream == nullptr) {
```
Comment (flamme) [inline apps/OboeTester/app/src/main/cpp/cpu/AudioWorkloadTest.h]: audioStream pointer will not be nullptr

Comment (robertwu1) [reply apps/OboeTester/app/src/main/cpp/cpu/AudioWorkloadTest.h]: Removed. Thanks!

**Review by flamme — APPROVED** [review]
