### PR TITLE
Fixed (potential) memory leak in WavStreamReader

### LINKED ISSUE #1213: Apparent memory leak in WavStreamReader
WavStreamReader allocates various chunks as raw pointers here:

https://github.com/google/oboe/blob/108a2cd854cc298e348b73a2638abd42bc1a6c32/samples/parselib/src/main/cpp/wav/WavStreamReader.cpp#L83

But I do not see where they are deleted!

They should be declared as std::unique_ptr.
Or, since they are small and are generally all needed when parsing, they could just be declared directly in place instead of being allocated at run-time.

### PR DESCRIPTION
**Pull request by android-usb**
Fixes #1213

### CODE REVIEW

File: samples/parselib/src/main/cpp/wav/WavStreamReader.h [hunk 1]
```diff
@@ -59,13 +59,13 @@ class WavStreamReader {
...
-    WavFmtChunkHeader *mFmtChunk;
-    WavChunkHeader *mDataChunk;
+    std::shared_ptr<WavRIFFChunkHeader> mWavChunk;
+    std::shared_ptr<WavFmtChunkHeader> mFmtChunk;
+    std::shared_ptr<WavChunkHeader> mDataChunk;
 
     long mAudioDataStartPos;
 
-    std::map<RiffID, WavChunkHeader *> *mChunkMap;
+    std::map<RiffID, std::shared_ptr<WavChunkHeader>> *mChunkMap;
```
Comment (philburk) [inline samples/parselib/src/main/cpp/wav/WavStreamReader.h:68]: I don't see where this map is used. Can we remove it?
Then we could use std::unique_ptr or, better yet, just declare the Chunks and not use new.

File: samples/parselib/src/main/cpp/wav/WavStreamReader.cpp [hunk 2]
```diff
@@ -39,7 +39,7 @@ WavStreamReader::WavStreamReader(InputStream *stream) {
 
     mAudioDataStartPos = -1;
 
-    mChunkMap = new std::map<RiffID, WavChunkHeader *>();
+    mChunkMap = new std::map<RiffID, std::shared_ptr<WavChunkHeader>>();
```
Comment (philburk) [inline samples/parselib/src/main/cpp/wav/WavStreamReader.cpp:42]: Where does this get deleted?

**Review by philburk — CHANGES_REQUESTED** [review]

File: samples/parselib/src/main/cpp/wav/WavStreamReader.h (hunk 1 above)
Comment (android-usb) [reply samples/parselib/src/main/cpp/wav/WavStreamReader.h:68]: It's there so that the WavStreamReader can evolve and also chunks that it doesn't recognize. I'd like to leave it and see how WavStreamReader evolves moving forward.

File: samples/parselib/src/main/cpp/wav/WavStreamReader.cpp (hunk 2 above)
Comment (android-usb) [reply samples/parselib/src/main/cpp/wav/WavStreamReader.cpp:42]: More to the point, why bother allocating it dynamically in any case?

File: samples/parselib/src/main/cpp/wav/WavStreamReader.cpp [hunk 3]
```diff
@@ -39,7 +39,7 @@ WavStreamReader::WavStreamReader(InputStream *stream) {
 
     mAudioDataStartPos = -1;
 
-    mChunkMap = new std::map<RiffID, WavChunkHeader *>();
+//    mChunkMap = new std::map<RiffID, std::shared_ptr<WavChunkHeader>>();
```
Comment (philburk) [inline samples/parselib/src/main/cpp/wav/WavStreamReader.cpp:42]: Dead code.

**Review by philburk — APPROVED** [review]
Thanks for fixing this.

File: samples/parselib/src/main/cpp/wav/WavStreamReader.cpp (hunk 3 above)
Comment (android-usb) [reply samples/parselib/src/main/cpp/wav/WavStreamReader.cpp:42]: Done.

**Review by philburk — APPROVED** [review]
When you submit the changes, please do a Squash and Merge from the GitHub UI.
