### PR TITLE
oboe: fix possible race on close

### LINKED ISSUE #1180: Thread safety gaps in AudioStreamAAudio
There are numerous method, eg. getTimestamp(), that reference the underlying native audio stream.
But that stream could get closed by an AAudio error callback that happened simultaneously.

    AAudioStream *stream = mAAudioStream.load();
    // <-- If close() occurred here then the stream would get used but the pointer is invalid!
    if (stream != nullptr) {

We need to lock around references to mAAudioStream.

### PR DESCRIPTION
**Pull request by philburk**
Protect native stream pointer with a shared_lock.

The race may have never ended badly.
But it was theoretically possible. So this prevents it.

Note that this requires that Oboe be built with C++17.
But apps can still use C++14.

Fixes #1180

### CODE REVIEW

File: apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp [hunk 1]
```diff
@@ -251,6 +258,20 @@ oboe::Result ActivityContext::start() {
         dataThread = new std::thread(threadCallback, this);
     }
 
+#ifdef DEBUG_CLOSE_RACE
```
Comment (dturner) [inline apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp:261]: If we are leaving this in, please add a comment explaining exactly what this directive is used for.

**Review by dturner — APPROVED** [review]
See comment

File: apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp (hunk 1 above)
Comment (philburk) [reply apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp:263]: Done.

**Review by dturner — APPROVED** [review]
